import React from 'react';
import {Cite} from '../references.jsx';
import results from '../data/results.json';
import {useCopy} from '../i18n.jsx';
import {Section,Figure,Bars,Details,DataTable,Setup,Conclusion,number} from '../ui.jsx';
import {MediaCard,ImageFigure} from '../media.jsx';
export function ClutterInterfaces(){
 const c=useCopy(),clip=id=>results.videos.find(v=>v.id===id);
 const counts=[['Open clutter · arrive + hold','开放杂乱场景 · 到达并停稳',3,3],['Open clutter · falls','开放杂乱场景 · 跌倒',0,1],['Low ceiling · arrive + hold','低顶棚 · 到达并停稳',1,0],['Low ceiling · falls','低顶棚 · 跌倒',1,3]];
 return <Section id="clutter-interfaces" index={c('S1 / MOTION-REFERENCE INTERFACES','S1 / 运动参考接口')} title={c('Clutter Scene · 5-point & 14-point','杂乱场景 · 五点与 14-point')} subtitle={c('Astra-authored trajectory generators executed by learned trackers','由 learned tracker 执行的 Astra 轨迹生成程序')}>
  <Setup methods={[
   ['5-point',c('An Astra-authored numeric or analytic generator uses clearance look-ahead to produce pelvis, wrist and ankle targets, which a learned five-point tracker executes.','Astra 编写的数值或解析生成器根据前方净空生成骨盆、双腕与双踝目标，再由 learned five-point tracker 执行。')],
   ['14-point',c('An Astra-authored generator constructs root and 29-joint references; forward kinematics converts them into 14 body targets for a learned whole-body tracker.','Astra 编写的生成器构造根部轨迹与 29 关节参考，正向运动学将其转换为 14 个身体部位目标，再交由 learned whole-body tracker 执行。')]
  ]}><p>{c('This study tests two motion-reference interfaces using programs written by Astra. Paired set01 covers open clutter and low ceilings, with easy, medium and hard scenes in both MuJoCo and PhysX: 12 runs per interface. Six additional five-point set02 runs bring the archive to 30. Strict passage requires no fall, less than 0.2 m endpoint error, a five-second stable hold, body points inside the runway and at most 5 N peak obstacle contact. We also measure arrival with a stable hold, falls, final XY position error and five-point tracking RMSE.','这组实验用 Astra 编写的程序检验两种运动参考接口。配对 set01 涵盖开放杂乱场景与低顶棚，每类在 MuJoCo 和 PhysX 上各运行 easy、medium、hard 场景，每接口共 12 次；另六次五点 set02 使完整记录共 30 次。严格通过要求不跌倒、终点误差小于 0.2 m、稳定保持五秒、身体点位于通道内，且障碍接触峰值不超过 5 N。此外分别记录到达并停稳、跌倒、最终 XY 位置误差与五点追踪 RMSE。')}<Cite ids={["mujoco","physx"]}/></p></Setup>

  <Figure title={c('Paired scene results · set01','配对场景结果 · set01')} subtitle={c('Counts / 6 runs per scene group and interface','计数 / 每场景组、每接口 6 次运行')} caption={c('Open clutter and low ceiling each cover easy / medium / hard scenes in MuJoCo and PhysX, with one run per scene/backend. Arrival and hold describe partial outcomes; strict pass also checks stability, runway bounds and contact. These runs evaluate generated programs; the preceding 25 × 65D experiment uses online Astra motion generation.','开放杂乱场景与低顶棚各包含 easy / medium / hard 场景在 MuJoCo 和 PhysX 上的运行，每个场景／后端一次。到达并停稳是部分结果；严格通过还检查稳定性、通道边界与接触。这组评估生成的程序，前述 25 × 65D 实验则由 Astra 在线生成运动参考。')}>
   <div className="charts-2">{counts.map(([en,zh,five,whole],i)=><div key={en}><div className="chart-title"><h4>{c(en,zh)}</h4><span>{i%2?c('Lower is better','越低越好'):c('Higher is better','越高越好')}</span></div><Bars max={6} rows={[{label:'5-point',value:five,display:five+'/6',color:'#5b7cff'},{label:'14-point',value:whole,display:whole+'/6',color:'#8fd6b4'}]}/></div>)}</div>
  </Figure>
  <DataTable caption={c('Combined paired set01 · 12 runs per interface','配对 set01 合计 · 每接口 12 次运行')} headers={[c('Interface','接口'),c('Strict pass','严格通过'),c('Arrive + hold','到达并停稳'),c('Falls','跌倒'),c('Final error m','最终误差 m'),c('5-point RMSE m','五点 RMSE m')]} rows={results.proxy.map(r=>[r.interface,r.strict_pass+'/'+r.episodes,r.arrive_hold+'/'+r.episodes,r.falls+'/'+r.episodes,number(r.final_error_m,3),number(r.fivepoint_rmse_m,3)])}/>
  <div className="prose"><h3>{c('5-point · clearance and simulator sensitivity','五点接口 · 净空与仿真后端差异')}</h3><p>{c('The generator uses clearance look-ahead to construct pelvis, wrist and ankle targets. The first low-ceiling clip reaches the goal but records a 2,364 N contact peak. In an extra set02 medium scene, the MuJoCo run arrives while the PhysX run falls at 24.88 s.','生成器根据前方净空构造骨盆、双腕与双踝目标。第一段低顶棚录像到达目标，但记录到 2,364 N 接触峰值。在额外的 set02 medium 场景中，MuJoCo 运行到达，而 PhysX 运行在 24.88 秒时跌倒。')}</p></div>
  <div className="media-grid"><MediaCard clip={clip('proxy-fivepoint-arrival')}/><MediaCard clip={clip('proxy-fivepoint-fall')}/></div>
  <div className="prose"><h3>{c('14-point · arrival and body clearance','14-point · 到达与身体净空')}</h3><p>{c('The generator constructs a root trajectory and 29 joint references, then uses forward kinematics to produce fourteen body targets. The open-clutter example arrives with a 6,057 N contact peak; the low-ceiling example strikes a beam with its torso and falls. Arrival alone therefore gives a different picture from strict passage through the course.','生成器构造根部轨迹与 29 个关节参考，再通过正向运动学得到十四部位目标。开放杂乱场景示例到达时记录到 6,057 N 接触峰值；低顶棚示例则因躯干撞梁而跌倒。因此，仅看终点到达，与严格通过整段路线呈现的结果不同。')}</p></div>
  <div className="media-grid"><MediaCard clip={clip('proxy-wholebody-arrival')}/><MediaCard clip={clip('proxy-wholebody-fall')}/></div>
  <Details title={c('All 30 runs, interface definitions and strict criteria','全部 30 次运行、接口定义与严格判据')}><p>{c('The full archive contains 18 five-point runs and 12 14-point runs. The comparison above uses the shared 12-run set01 subset; six extra five-point low-ceiling set02 runs remain in the full table below. All 30 have zero strict course and reference-tracking passes.','完整记录包含 18 次五点运行与 12 次 14-point 运行。上方比较使用共同的 12 次 set01 子集；额外六次五点低顶棚 set02 运行保留在下方总表。全部 30 次的严格路线与参考跟踪通过数均为零。')}</p><ImageFigure src="media/joint/proxy-all-results.png" alt={c('Summary of all thirty interface diagnostic runs','全部三十次接口诊断运行汇总')} caption={c('Summary of all 30 runs. The five-point low-ceiling row combines set01 and set02; the paired comparison uses set01 only.','全部 30 次运行的汇总。五点低顶棚一行合并 set01 与 set02；配对比较仅使用 set01。')}/><p>{c('Strict pass requires no fall, final XY error below 0.2 m, a stable five-second hold, all five body points within the runway and peak obstacle contact at most 5 N. Contact-force columns average per-run peaks; MuJoCo and PhysX use different contact solvers.','严格通过要求不跌倒、最终 XY 误差小于 0.2 m、稳定保持五秒、身体五点处于通道内，且障碍接触峰值不超过 5 N。接触力列为逐次运行峰值的平均值；MuJoCo 与 PhysX 使用不同接触求解器。')}</p><DataTable headers={[c('Interface','接口'),c('Travel m','行进距离 m'),c('Mean peak contact N','平均峰值接触 N'),c('Mean peak non-foot contact N','平均峰值非足部接触 N')]} rows={results.proxy.map(r=>[r.interface,number(r.travel_m,3),number(r.mean_peak_contact_n),number(r.mean_nonfoot_contact_n)])}/></Details>
  <Conclusion paragraphs={c(["On the paired set01 scenes, the five-point generator arrives and holds in 4/12 runs, compared with 3/12 for 14-point, and falls in 1/12 rather than 4/12. The reduced reference interface is more stable in this tested set, particularly under low ceilings.","Both interfaces record zero strict course passes. Some arriving runs have large obstacle-contact peaks, and the low-ceiling examples expose body-clearance failures. The experiments show that an Astra-authored trajectory generator can produce useful movement over a learned tracker, while contact limits and full-body clearance remain essential constraints on completing the route."],["配对 set01 场景中，五点生成器到达并停稳为 4/12，14-point 为 3/12；跌倒分别为 1/12 与 4/12。在这组测试中，较简化的五点参考接口更稳定，低顶棚场景尤其明显。","两种接口的严格路线通过数均为零。部分到达记录伴随较大的障碍接触峰值，低顶棚案例也暴露出身体净空不足。Astra 编写的轨迹生成程序能借助 learned tracker 生成可执行运动，而接触限值与全身净空仍是完成整段路线的关键约束。"])}/>
  <div className="sec-links"><a href="joint-data/proxy-paired-set01.csv" download>{c('Paired interface data · CSV ↓','配对接口数据 · CSV ↓')}</a></div>
 </Section>;
}
ClutterInterfaces.meta={id:'clutter-interfaces',title:{en:'5-point & 14-point',zh:'五点与 14-point'}};
