import React from 'react';
import {Cite} from '../references.jsx';
import {useCopy} from '../i18n.jsx';
import {Section,Figure,Bars,DataTable,Setup,Conclusion} from '../ui.jsx';
import {MediaCard} from '../media.jsx';
import {dexterousTasks as tasks,dexterousVideos as videos,dexterousMeans} from '../data/dexterous.js';
export function DexterousManipulation(){
 const c=useCopy();
 return <Section id="dexterous-manipulation" index={c('S1 ↔ S2 / DEXTEROUS MANIPULATION','S1 ↔ S2 / 灵巧操作')} title={c('Dexterous Manipulation','灵巧操作')} subtitle={c('10 simulated tasks · arm, wrist and finger coordination','10 项仿真任务 · 手臂、手腕与手指协同')}>
  <div className="prose"><h4>{c('Task design and initial scenes','任务设计与初始场景')}</h4><p>{c('The suite covers grasp maintenance, retrieval, placement, insertion, stacking and multi-object rearrangement. Instructions specify object identity, orientation, containment, support, category-dependent destinations and size ordering. The nine panels show task initial states; the results table includes all ten tasks.','任务涵盖持续抓握、取物、放置、插入、堆叠及多物体重排。指令涉及物体选择、朝向、容纳、支撑、按类别指定放置位置和按大小排序。下方九张图展示任务初态，结果表涵盖全部十项任务。')}</p><div className="scene-grid">{tasks.filter(r=>r.initial).map(r=><figure key={r.task}><a href={'media/dexterous/init/'+r.initial+'.jpg'} target="_blank" rel="noreferrer"><img src={'media/dexterous/init/'+r.initial+'.jpg'} alt={c(r.task+' · initial state',r.zh+' · 初始场景')} loading="lazy" width="720" height="450"/></a><figcaption>{c(r.task,r.zh)}</figcaption></figure>)}</div></div>
  <Setup methods={[
   ['π₀.₅',c('Observation + task → finetuned multi-task policy → arm, wrist and finger actions.','观测 + 任务 → 微调后的多任务策略 → 手臂、手腕与手指动作。')],
   ['Astra',c('Observation + task → Astra chooses arm and hand targets → execution controller.','观测 + 任务 → Astra 选择手臂与手部目标 → 执行控制器。')],
   ['Astra + π₀.₅',c('The same π₀.₅ proposes actions → Astra reviews and corrects the trajectory → execution controller.','同一 π₀.₅ 提供候选动作 → Astra 审核并修正轨迹 → 执行控制器。')]
  ]}><p>{c('Ten simulated tasks test grasp maintenance, retrieval, constrained placement, insertion, stacking and object sorting. Instructions specify identity, orientation and destination, requiring coordinated arm and finger motion. A single multi-task π₀.₅ is finetuned on 100 demonstrations per task (1,000 total). Evaluation scores partial completion of subgoals on a 0–100 scale.','十项仿真任务检验持续抓握、取物、约束放置、插入、堆叠与物体分类。指令指定物体、朝向与目的地，需要手臂和手指协同。单个多任务 π₀.₅ 基于每任务 100 条、共 1,000 条示范微调；评测以 0–100 的子目标 Score 计入部分完成度。')}<Cite ids={["pi05"]}/></p></Setup>
  <Figure title={c('Dexterous task scores','灵巧操作任务得分')} subtitle={c('Subgoal completion · Score 0–100','子目标完成度 · Score 0–100')} caption={c('Unweighted mean across ten task scores. The π₀.₅ and Astra + π₀.₅ conditions use the same multi-task π₀.₅ policy, finetuned on 100 demonstrations per task (1,000 total).','十项任务得分的等权均值。π₀.₅ 与 Astra + π₀.₅ 使用同一多任务 π₀.₅，基于每任务 100 条、共 1,000 条示范微调。')}>
   <Bars unit="" decimals={1} rows={[{label:'π₀.₅',value:dexterousMeans.pi05,method:'baseline'},{label:'Astra',value:dexterousMeans.direct,method:'gpt'},{label:'Astra + π₀.₅',value:dexterousMeans.hybrid,method:'hybrid'}]}/>
  </Figure>
  <DataTable className="table-dex" caption={c('Task scores · 0–100','逐任务 Score · 0–100')} headers={[c('Task','任务'),'π₀.₅','Astra','Astra + π₀.₅']} rows={tasks.map(r=>[c(r.task,r.zh),r.pi05.toFixed(1),r.direct.toFixed(1),r.hybrid.toFixed(1)])}/>
  <div className="prose"><h3>{c('Astra · choosing arm and hand targets','Astra · 同时选择手臂与手部目标')}</h3><p>{c('Astra specifies arm and hand targets over the execution controller. Its scores exceed π₀.₅ on pot lifting (44 versus 40) and egg placement (12 versus 6), while remaining lower on the other eight tasks. The two illustrated episodes show difficulties in forming a grasp: the hand repeatedly realigns in the pot episode, and its outer surface contacts the bottle before the fingers can enclose it in the sorting episode.','Astra 通过执行控制器指定手臂与手部目标，在提锅（44 对 40）和鸡蛋放置（12 对 6）上的得分高于 π₀.₅，其余八项较低。下方两个回合展示了形成有效抓握时的困难：提锅回合中手部持续重新对准；瓶罐分类回合中，手部外侧在手指包覆物体之前先发生接触。')}</p></div>
  <div className="media-grid">{videos.slice(0,2).map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div>
  <div className="prose"><h3>{c('Astra + π₀.₅ · trajectory correction and grasp control','Astra + π₀.₅ · 轨迹修正与抓握控制')}</h3><p>{c('π₀.₅ supplies the action proposals, while Astra reviews and corrects them. In the egg and mahjong examples, the policy executes most control steps and Astra mainly adjusts wrist position by a few centimeters. Mahjong retains the policy’s finger configurations throughout; the egg example also contains hand edits in its first intervention burst. These cases show how Astra’s scene-level corrections complement the grasp and finger control supplied by π₀.₅.','π₀.₅ 提供候选动作，Astra 负责审核与修正。在鸡蛋和麻将案例中，大多数控制步由策略执行，Astra 主要对手腕位置作厘米级调整。麻将全程保留策略的手指配置；鸡蛋案例的首段介入也包含手部配置修正。这些案例展示了 Astra 的场景级修正与 π₀.₅ 的抓握和手指控制如何形成互补。')}</p></div>
  <div className="media-grid">{videos.slice(2).map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div>

  <Conclusion paragraphs={c(["Astra + π₀.₅ reaches a mean Score of 61.8, compared with 44.2 for π₀.₅ and 16.6 for Astra, a 17.6-point gain over π₀.₅. The combination improves eight task scores and ties on headphone placement and toy retrieval. The largest gains are in mahjong placement (+40), egg placement (+32) and bottle-and-can sorting (+28). Bread insertion reaches 28 versus 10, nesting-doll arrangement 26 versus 16, and bowl stacking 52 versus 46. Astra exceeds π₀.₅ on pot lifting and egg placement, while its ten-task mean remains lower.","The egg and mahjong rollouts show how the combination helps: π₀.₅ sustains the grasp and executes most steps, while Astra adjusts wrist placement or moves an occluding hand. These corrections can improve object placement without requiring Astra to reconstruct the entire finger-control sequence. Across the ten tasks, combining this scene-level reasoning with the policy’s grasp and finger control yields higher or equal scores than π₀.₅. Grasp formation and sustained contact remain the main difficulties in the Astra examples."],["Astra + π₀.₅ 的平均 Score 为 61.8，π₀.₅ 为 44.2，Astra 为 16.6，组合方法比 π₀.₅ 平均高 17.6 分。十项任务中，八项得分提升，耳机放置和玩具取出两项持平。提升最大的是麻将放置（+40 分）、鸡蛋放置（+32 分）和瓶罐分类（+28 分）。面包插入为 28 对 10 分，套娃排列为 26 对 16 分，叠碗为 52 对 46 分。Astra 在提锅和鸡蛋放置上高于 π₀.₅，但十项任务的平均得分仍较低。","鸡蛋与麻将案例说明了组合方法的作用：π₀.₅ 维持抓握并执行大部分动作，Astra 调整手腕位置或移开遮挡的手。这些修正改善了物体放置，也保留了策略已有的手指控制序列。在这十项任务中，将场景级推理与策略的抓握、手指控制结合，各项得分均达到或超过 π₀.₅。Astra 单独控制时，形成有效抓握与维持接触仍是主要困难。"])}/>
  <div className="sec-links"><a href="joint-data/dexterous-scores.csv" download>{c('All task scores and instructions · CSV ↓','全部任务得分与指令 · CSV ↓')}</a></div>
 </Section>;
}
DexterousManipulation.meta={id:'dexterous-manipulation',title:{en:'Dexterous Manipulation',zh:'灵巧操作'}};
