import React,{useState} from 'react';
import {Cite} from '../references.jsx';
import {useCopy,useLanguage} from '../i18n.jsx';
import {viewHref} from '../site.js';
import {Section,Figure,Bars,Details,DataTable,Toggle,Setup,Conclusion,number} from '../ui.jsx';
import {MediaCard,ImageFigure} from '../media.jsx';
import {dexS0Rotation,dexS0Translation,dexS0TranslationMeans,dexS0Combined,dexS0CombinedMeans,dexS0Clip} from '../data/dex-s0.js';
export function DexterousS0(){
 const c=useCopy(),{language}=useLanguage(),[metric,setMetric]=useState('goal');
 const metrics={goal:[c('At-goal · % of evaluated steps ↑','目标内步数占比 · % ↑'),100,2],error:[c('Mean orientation error · rad ↓','平均朝向误差 · rad ↓'),1.8,3],speed:[c('Axial-speed MAE · rad/s ↓','轴向速度 MAE · rad/s ↓'),1,3]};
 const [label,max,decimals]=metrics[metric];
 const endpoints=[['astra','Astra','gpt'],['matched',c('RL · matched steps','RL · 相同步数'),'baseline'],['rl','RL · 15 s','baseline']];
 const combinedRows=metric=>endpoints.map(([key,label,method])=>({label,method,value:dexS0CombinedMeans[key][metric],...(key==='matched'?{color:'#c9d3ff'}:{})}));
 const result=value=>value?c('Success','成功'):c('Failure','失败');
 const pair=value=>number(value.position,2)+' / '+number(value.rotation,2);
 return <Section id="dexterous-s0" index={c('S0 / DIRECT FINGER CONTROL','S0 / 直接手指控制')} title={c('In-hand Manipulation','手内操作')} subtitle={c('Sharpa & Allegro · four tasks · five paired states per task','Sharpa 与 Allegro · 四项任务 · 每任务五组配对初态')}>
  <Setup methods={[
   ['Astra',c('Synchronized images + hand/object state → Astra → bounded finger joint-target increments → hand controller. Evaluation reward is withheld.','同步图像 + 手部／物体状态 → Astra → 有界手指关节目标增量 → 手部控制器；奖励仅用于评测。')],
   ['RL',c('Native policy observations → specialized task policy → hand controller. Both methods start from the same saved hand state, object state and target, retaining their native inference rates.','原生策略观测 → 专用任务策略 → 手部控制器。两种方法从相同保存的手部状态、物体状态与目标开始，保留各自原生推理频率。')]
  ]}><p>{c('Four tasks isolate finger-level contact control, with five paired initial states per task. Sharpa / PTrack tracks continuous world-Z rotation of a cylinder at 1.0 rad/s for 20 s and a cuboid at 0.2 rad/s for 10 s. Allegro / tactile IHT tests two fixed goals: translating a cylinder to a target position, and combining translation with a −40° rotation about its long axis. These tasks have a 15 s horizon; the combined task also limits Astra to 120 decisions.','四项任务检验手指层面的接触控制，每项使用五组配对初态。Sharpa / PTrack 追踪绕世界 Z 轴的连续旋转：圆柱以 1.0 rad/s 旋转 20 秒，长方体以 0.2 rad/s 旋转 10 秒。Allegro / tactile IHT 包含两项固定目标任务：将圆柱平移到目标位置，以及同时完成平移和绕长轴 −40° 的旋转。两项任务的时长上限为 15 秒，联合任务另设 Astra 120 次决策上限。')}<Cite ids={["sharpa","allegro"]}/></p>
  <ImageFigure src="media/dex-s0/benchmark_overview-0920.png" mobileSrc="media/dex-s0/benchmark_overview-0920-mobile.png" alt={c('Task schematic: cylinder rotation, cuboid rotation, cylinder translation and translation with rotation','任务示意：圆柱旋转、长方体旋转、圆柱平移、平移与旋转')} caption={c('Task configurations, in reading order. The first two tasks track a continuously moving orientation target. The third moves the cylinder center to a fixed position; the fourth adds a −40° long-axis rotation. Arrows indicate the requested motions. Each task compares Astra and RL from the same five saved initial states and targets.','图中依次为四项任务的示意图。前两项追踪持续变化的朝向目标；第三项将圆柱中心移至固定位置；第四项同时要求绕长轴旋转 −40°。箭头表示要求的运动方向。每项任务均从相同的五组保存初态和目标比较 Astra 与 RL。')}/>
  <p>{c('Continuous rotation is evaluated by orientation error, axial-speed MAE and the fraction of steps within the orientation tolerance. Fixed-goal tasks use terminal position error and success, with terminal rotation error added for the combined task. Position tolerance is approximately 22.4 mm; combined-task success also requires rotation error below 10° at the same endpoint. Object drops are recorded for all four tasks.','连续旋转使用朝向误差、轴向速度 MAE 和朝向容差内的步数占比；固定目标任务使用终点位置误差与成功数，联合任务另评估终点旋转误差。位置容差约为 22.4 mm，联合任务还要求同一终点的旋转误差小于 10°。四项任务均记录物体掉落情况。')}</p>
  </Setup>


  <Figure title={c('Continuous rotation','连续旋转')} subtitle={label} caption={c('Sharpa / PTrack · metrics pooled over the recorded evaluation steps; world-frame +Z rotation, at 1.0 rad/s for the cylinder (20 s) and 0.2 rad/s for the cuboid (10 s). At-goal is the fraction of evaluated steps with quaternion geodesic error < 0.1 rad. It is a step-level measure. Read it alongside axial-speed MAE because orientation error is periodic.','Sharpa / PTrack · 指标合并记录的评测步统计；绕世界坐标 +Z 旋转：圆柱 1.0 rad/s、20 秒，长方体 0.2 rad/s、10 秒。目标内占比为四元数测地误差 < 0.1 rad 的评测步数比例。该指标按步统计；朝向误差具有周期性，需结合轴向速度 MAE 阅读。')}>
   <Toggle label={c('Rotation metric','旋转指标')} value={metric} onChange={setMetric} options={[[ 'goal',c('At-goal','目标内占比')],['error',c('Orientation error','朝向误差')],['speed',c('Speed MAE','速度 MAE')]]}/>
   <div className="charts-2">{dexS0Rotation.map(r=><div key={r.id}><div className="chart-title"><h4>{c(r.en,r.zh)}</h4><span>{r.duration} s</span></div><Bars max={max} decimals={decimals} unit={metric==='goal'?'%':''} rows={[{label:'Astra',value:r.astra[metric],method:'gpt'},{label:'RL',value:r.rl[metric],method:'baseline'}]}/></div>)}</div>
   <DataTable className="table-wide" caption={c('Episode duration and retention · full horizon is separate from tracking accuracy','轨迹时长与物体保持 · 完整运行与追踪精度分别统计')} headers={[c('Task','任务'),c('Controller','控制器'),c('Full horizon','完整时长'),c('Drop','掉落'),c('Evaluated steps','评测步数')]} rows={dexS0Rotation.flatMap(r=>[['Astra',r.astra],['RL',r.rl]].map(([method,v])=>[c(r.en,r.zh),method,v.full+'/5',v.drop+'/5',number(v.steps)]))}/>
  </Figure>
  <div className="media-grid"><MediaCard clip={dexS0Clip('cylinder_case_004')}/><MediaCard clip={dexS0Clip('cuboid_case_004_10s')}/></div>
  <Details title={c('Rotation trajectories and all ten paired cases','旋转轨迹与全部十组配对案例')}><ImageFigure src="media/dex-s0/rotation_trajectories-astra.png" alt={c('Rotation trajectories: orientation error, axial speed, at-goal and return','旋转轨迹：朝向误差、轴向速度、目标内占比与回报')} caption={c('Means over the available case trajectories at each time, with standard-deviation bands. Astra cylinder traces can end early, so contributing cases change over time. Speed uses a trailing one-second window of unwrapped world-Z rotation.','逐时刻对仍有记录的案例取均值，阴影为标准差。Astra 圆柱轨迹可能提前结束，各时刻参与统计的案例数会变化。速度取展开后的世界 Z 轴旋转在此前一秒窗口内的变化。')}/><ImageFigure src="media/dex-s0/rotation_per_case-astra.png" alt={c('Per-case orientation error, speed MAE, at-goal and return for all ten rotation pairs','全部十组旋转配对的朝向误差、速度 MAE、目标内占比与回报')} caption={c('All five cases per object. Returns are interpreted within each task and with its executed step count. All ten synchronized comparisons are available in the S0 gallery.','每种物体五组案例。回报在各自任务内结合执行步数阅读；全部十段同步对照可在 S0 视频库查看。')}/></Details>
  <div className="prose" id="dex-s0-translation"><h3>{c('Cylinder translation','圆柱平移')}</h3><p>{c('The cylinder must finish within 22.4 mm of its target position while remaining in the hand. Both controllers run 300 control steps, or 15 s, from each of five paired initial states. Final position error measures the remaining displacement; success is determined at the terminal state.','任务要求圆柱在结束时保持于手中，且中心距目标位置小于 22.4 mm。两种控制器均从五组配对初态运行 300 个控制步，即 15 秒。终点位置误差衡量剩余位移，成功与否按终点状态判定。')}</p></div>
  <Figure title={c('Translation endpoints','平移终点结果')} subtitle={c('Five paired states · 15 s','五组配对初态 · 15 秒')} caption={c('Mean terminal error across five cases. The dashed line marks the position tolerance of approximately 22.4 mm. Both methods complete the full horizon without dropping the object.','五组案例的平均终点误差。虚线标出约 22.4 mm 的位置容差。两种方法均运行至完整时长且未掉落物体。')}>
   <div className="charts-2"><div><div className="chart-title"><h4>{c('Final position error · mm ↓','终点位置误差 · mm ↓')}</h4></div><Bars unit=" mm" max={70} threshold={Math.sqrt(.0005)*1000} decimals={2} rows={[{label:'Astra',value:dexS0TranslationMeans.astra,method:'gpt'},{label:'RL',value:dexS0TranslationMeans.rl,method:'baseline'}]}/></div><div><div className="chart-title"><h4>{c('Final success · cases ↑','最终成功 · 案例 ↑')}</h4></div><Bars max={5} rows={[{label:'Astra',value:1,display:'1/5',method:'gpt'},{label:'RL',value:4,display:'4/5',method:'baseline'}]}/></div></div>
  </Figure>
  <DataTable headers={[c('Sample','样本'),c('Astra · mm ↓','Astra · mm ↓'),c('Outcome','结果'),c('RL · mm ↓','RL · mm ↓'),c('Outcome','结果')]} rows={dexS0Translation.map(r=>[r.id,number(r.astra.position,2),result(r.astra.success),number(r.rl.position,2),result(r.rl.success)])} caption={c('Terminal position error and success for each paired initial state','各配对初态的终点位置误差与成功情况')}/>
  <div className="prose"><p>{c('RL finishes closer to the target in four of five cases, with mean final error of 17.29 mm versus Astra’s 59.05 mm. Sample 001 has the shortest initial target displacement: Astra reaches the target and finishes at 19.13 mm, while RL enters the target region but later leaves it, ending at 31.12 mm. This case shows that Astra can make a useful local repositioning, while the other four states favor the specialized policy.','RL 在五组中的四组更接近目标，平均终点误差为 17.29 mm，Astra 为 59.05 mm。样本 001 的初始目标位移最短：Astra 到达目标，最终误差为 19.13 mm；RL 曾进入目标区域，但随后离开，最终误差为 31.12 mm。该案例展示了 Astra 完成局部重新定位的能力，另外四组初态则由专用策略表现更好。')}</p></div>
  <div className="media-grid"><MediaCard clip={dexS0Clip('translation_sample_000')}/><MediaCard clip={dexS0Clip('translation_sample_001')}/></div>

  <div className="prose" id="dex-s0-translation-rotation"><h3>{c('Translation + rotation','平移与旋转')}</h3>
   <p>{c('The cylinder must reach a Cartesian position and rotate −40° about its long axis. Success requires both position error below approximately 22.4 mm and rotation error below 10° at the same endpoint. Five stabilized hand–object states are paired between Astra and RL. Astra receives front, opposite and top RGB views, hand proprioception, object and target states, and signed tactile readings. It outputs 16 joint-target increments; each command may repeat for one to five 50 ms control steps. The task-specific RL policy uses its native observations and produces actions at every control step.','任务要求圆柱到达笛卡尔目标位置，同时绕长轴旋转 −40°。成功要求同一终点的位置误差小于约 22.4 mm、旋转误差小于 10°。Astra 与 RL 从五组稳定后的手部／物体状态配对开始。Astra 接收正面、对面和俯视 RGB 图像，以及手部本体状态、物体与目标状态和带符号触觉读数，输出 16 个关节目标增量；每条指令可重复执行一至五个 50 ms 控制步。任务专用 RL policy 使用原生观测，在每个控制步生成动作。')}</p>
   <p>{c('Astra has a budget of 120 decisions and reaches it after 120–153 control steps, or 6.00–7.65 s. We compare its endpoint with RL at the same per-case control step, then report RL at the full 300-step, 15 s horizon.','Astra 的预算为 120 次决策，各案例在执行 120–153 个控制步、即 6.00–7.65 秒后用完。我们比较 Astra 的终点与 RL 在该案例相同控制步数下的状态，并另列 RL 完成 300 步、15 秒后的结果。')}</p>
  </div>
  <Figure title={c('Joint position and rotation goals','位置与旋转联合目标')} subtitle={c('Five paired states','五组配对初态')} caption={c('Errors are averaged across the five terminal states. Dashed lines mark the position and rotation tolerances. RL · matched steps uses 153, 129, 134, 120 and 132 steps for samples 000–004; RL · 15 s uses 300 steps for every sample. Astra’s endpoint is fixed by its 120-decision budget. Neither controller drops the object.','误差为五组终点状态的均值，虚线分别标出位置与旋转容差。RL 的相同步数结果对应样本 000–004 的 153、129、134、120、132 步；RL · 15 s 均为 300 步。Astra 的终点由 120 次决策预算确定。两种控制器均未掉落物体。')}>
   <div className="charts-2"><div><div className="chart-title"><h4>{c('Final position error · mm ↓','终点位置误差 · mm ↓')}</h4></div><Bars max={55} unit=" mm" decimals={2} threshold={Math.sqrt(.0005)*1000} rows={combinedRows('position')}/></div><div><div className="chart-title"><h4>{c('Final rotation error · ° ↓','终点旋转误差 · ° ↓')}</h4></div><Bars max={40} unit="°" decimals={2} threshold={10} rows={combinedRows('rotation')}/></div></div>
   <DataTable headers={[c('Controller / endpoint','控制器／评测终点'),c('Duration · s','时长 · 秒'),c('Joint success','联合成功'),c('Object drop','物体掉落')]} rows={endpoints.map(([key,label])=>[label,key==='rl'?'15.00':'6.00–7.65',dexS0CombinedMeans[key].success+'/5','0/5'])}/>
  </Figure>
  <DataTable className="table-wide" headers={[c('Sample','样本'),c('Matched time · s','配对时刻 · 秒'),'Astra',c('RL · matched steps','RL · 相同步数'),'RL · 15 s']} rows={dexS0Combined.map(r=>[r.id,number(r.steps*.05,2),pair(r.astra),pair(r.matched),pair(r.rl)])} caption={c('Each cell reports terminal position error (mm) / rotation error (degrees); both must meet their thresholds for success.','各单元格为终点位置误差（mm）／旋转误差（度）；两者均满足容差才判为成功。')}/>
  <div className="prose"><p>{c('Astra retains the object but meets neither terminal threshold in any of the five cases. At the matched endpoints, RL brings every case within the position tolerance and four within the rotation tolerance. Sample 002 has 21.70° remaining rotation error at 6.70 s; this falls to 5.71° at 15 s, bringing the fifth case into the joint success region. RL’s mean terminal position / rotation errors are 16.22 mm / 8.31° at the matched endpoints and 16.08 mm / 3.49° at 15 s, compared with Astra’s 47.35 mm / 32.72°.','Astra 保持了物体，但五组案例在终点均未满足位置或旋转容差。相同步数下，RL 的五组案例均满足位置容差，四组同时满足旋转容差。样本 002 在 6.70 秒时还剩 21.70° 旋转误差，到 15 秒时降至 5.71°，第五组也达到联合目标。RL 的平均终点位置／旋转误差在相同步数下为 16.22 mm／8.31°，15 秒时为 16.08 mm／3.49°，Astra 则为 47.35 mm／32.72°。')}</p></div>
  <MediaCard clip={dexS0Clip('translation_rotation_sample_003_comparison')}/>
  <Conclusion paragraphs={c([
   'The specialized RL policies track both continuously rotating targets more accurately. Astra stays within the orientation tolerance for 0.51% of evaluated cylinder steps, versus 76.90% for RL; for the cuboid, the values are 4.40% and 63.50%. Holding the object and completing a rollout therefore remain distinct from tracking the commanded motion.',
   'For fixed-goal translation, both methods retain the object in all five cases. Astra succeeds once and RL four times, with mean final position errors of 59.05 mm and 17.29 mm. Astra’s successful case has the shortest initial displacement and ends at 19.13 mm error, demonstrating useful local repositioning.',
   'Requiring position and rotation together increases the coordination demands. Astra reaches neither terminal tolerance before its 120-decision budget, while RL meets both in four of five cases at the same control-step endpoints and in all five after 15 s. Across these tasks, Astra can preserve contact and occasionally achieve a local goal; the specialized policy is more consistent at coordinating finger contacts to track or reach the requested object motion.'
  ],[
   '专用 RL policy 对两种连续旋转目标的追踪均更准确。圆柱任务中，Astra 处于朝向容差内的步数占比为 0.51%，RL 为 76.90%；长方体任务分别为 4.40% 与 63.50%。保持物体并完成轨迹，与准确追踪要求的运动仍是不同能力。',
   '固定目标平移中，两种方法在五组初态下均未掉落物体。Astra 成功一组，RL 成功四组，平均终点位置误差分别为 59.05 mm 和 17.29 mm。Astra 成功的案例具有最短初始位移，最终误差为 19.13 mm，展示了有效的局部重新定位。',
   '同时要求位置与旋转时，手指协调的要求进一步增加。Astra 在用完 120 次决策预算时，五组均未满足任一终点容差；RL 在相同控制步数下有四组同时满足两项容差，15 秒时五组全部成功。综合四项任务，Astra 能保持接触，并在部分初态下完成局部目标；专用策略在协调手指接触、追踪或到达要求的物体运动方面更稳定。'
  ])}/>
  <div className="sec-links"><a href="joint-data/dex-s0-task_summary.csv" download>{c('Four-task summary · CSV ↓','四项任务汇总 · CSV ↓')}</a><a href="joint-data/dex-s0-translation_cases.csv" download>{c('Translation endpoints · CSV ↓','平移终点数据 · CSV ↓')}</a><a href="joint-data/dex-s0-translation_rotation_matched_windows.csv" download>{c('Matched endpoints · CSV ↓','联合任务配对终点 · CSV ↓')}</a><a href="joint-data/dex-s0-translation_rotation_cases.csv" download>{c('Combined-task endpoints · CSV ↓','联合任务终点数据 · CSV ↓')}</a><a href={viewHref('gallery',language,{setting:'dexterous',level:'s0'})}>{c('All 20 comparison videos ↗','全部 20 段对照视频 ↗')}</a></div>
 </Section>;
}
DexterousS0.meta={id:'dexterous-s0',title:{en:'In-hand Manipulation',zh:'手内操作'}};
