import React from 'react';
import {Cite} from '../references.jsx';
import {useCopy,useLanguage} from '../i18n.jsx';
import {viewHref} from '../site.js';
import {Section,Figure,Bars,DataTable,Setup,Conclusion} from '../ui.jsx';
import {MediaCard} from '../media.jsx';
import {dexterousTasks as tasks,dexterousMeans} from '../data/dexterous.js';
import {dexInitialTasks,dexDirectFailures,dexHybridSuccesses,dexHybridLimitations} from '../data/dexterous-s1.js';
export function DexterousManipulation(){
 const c=useCopy(),{language}=useLanguage();
 return <Section id="dexterous-manipulation" index={c('S1 ↔ S2 / DEXTEROUS MANIPULATION','S1 ↔ S2 / 灵巧操作')} title={c('Dexterous Manipulation','灵巧操作')} subtitle={c('10 simulated tasks · arm, wrist and finger coordination','10 项仿真任务 · 手臂、手腕与手指协同')}>
  <div className="prose"><h4>{c('Task design and initial scenes','任务设计与初始场景')}</h4><p>{c('The suite covers grasp maintenance, retrieval, placement, insertion, stacking and multi-object rearrangement. Instructions specify object identity, orientation, containment, support, category-dependent destinations and size ordering. The eight panels show task initial states; the results table includes all ten tasks.','任务涵盖持续抓握、取物、放置、插入、堆叠及多物体重排。指令涉及物体选择、朝向、容纳、支撑、按类别指定放置位置和按大小排序。下方八张图展示任务初态，结果表涵盖全部十项任务。')}</p><div className="scene-grid">{dexInitialTasks.map(r=><figure key={r.task}><a href={'media/dexterous/s1-0920/initial/'+r.id+'.jpg'} target="_blank" rel="noreferrer"><img src={'media/dexterous/s1-0920/initial/'+r.id+'.jpg'} alt={c(r.task+' · initial state',r.zh+' · 初始场景')} loading="lazy" width="1280" height="720"/></a><figcaption>{c(r.task,r.zh)}</figcaption></figure>)}</div></div>
  <Setup methods={[
   ['π₀.₅',c('Observation + task → finetuned multi-task policy → arm, wrist and finger actions.','观测 + 任务 → 微调后的多任务策略 → 手臂、手腕与手指动作。')],
   ['Astra',c('Observation + task → Astra chooses arm and hand targets → execution controller.','观测 + 任务 → Astra 选择手臂与手部目标 → 执行控制器。')],
   ['Astra + π₀.₅',c('The same π₀.₅ proposes actions → Astra reviews and corrects the trajectory → execution controller.','同一 π₀.₅ 提供候选动作 → Astra 审核并修正轨迹 → 执行控制器。')]
  ]}><p>{c('Ten simulated tasks test grasp maintenance, retrieval, constrained placement, insertion, stacking and object sorting. Instructions specify identity, orientation and destination, requiring coordinated arm and finger motion. A single multi-task π₀.₅ is finetuned on 100 demonstrations per task (1,000 total). Evaluation scores partial completion of subgoals on a 0–100 scale.','十项仿真任务检验持续抓握、取物、约束放置、插入、堆叠与物体分类。指令指定物体、朝向与目的地，需要手臂和手指协同。单个多任务 π₀.₅ 基于每任务 100 条、共 1,000 条示范微调；评测以 0–100 的子目标 Score 计入部分完成度。')}<Cite ids={["pi05"]}/></p></Setup>
  <Figure title={c('Dexterous task scores','灵巧操作任务得分')} subtitle={c('Subgoal completion · Score 0–100','子目标完成度 · Score 0–100')} caption={c('Unweighted mean across ten task scores. The π₀.₅ and Astra + π₀.₅ conditions use the same multi-task π₀.₅ policy, finetuned on 100 demonstrations per task (1,000 total).','十项任务得分的等权均值。π₀.₅ 与 Astra + π₀.₅ 使用同一多任务 π₀.₅，基于每任务 100 条、共 1,000 条示范微调。')}>
   <Bars unit="" decimals={1} rows={[{label:'π₀.₅',value:dexterousMeans.pi05,method:'baseline'},{label:'Astra',value:dexterousMeans.direct,method:'gpt'},{label:'Astra + π₀.₅',value:dexterousMeans.hybrid,method:'hybrid'}]}/>
  </Figure>
  <DataTable className="table-dex" caption={c('Task scores · 0–100','逐任务 Score · 0–100')} headers={[c('Task','任务'),'π₀.₅','Astra','Astra + π₀.₅']} rows={tasks.map(r=>[c(r.task,r.zh),r.pi05.toFixed(1),r.direct.toFixed(1),r.hybrid.toFixed(1)])}/>
  <div className="prose"><h3>{c('Astra · grasp formation and contact control','Astra · 抓握形成与接触控制')}</h3><p>{c('Astra specifies arm and hand targets over the execution controller. It scores above π₀.₅ on pot lifting (44 versus 40) and egg placement (12 versus 6), but below it on the other eight tasks. The two failure cases illustrate difficulties in forming a stable grasp while controlling contact: reaching into the toy bin displaces the container, while repeated hand and wrist adjustments disturb the objects and baskets during bottle-and-can sorting.','Astra 通过执行控制器指定手臂与手部目标，在提锅（44 对 40）和鸡蛋放置（12 对 6）上的得分高于 π₀.₅，其余八项较低。两个失败案例体现了稳定抓握与接触控制的困难：箱内取物时，手部接触带动容器移动；瓶罐分类时，反复调整手型与手腕扰动了物体和篮筐。')}</p></div>
  <div className="media-grid">{dexDirectFailures.map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div>
  <div className="prose"><h3>{c('Astra + π₀.₅ · trajectory correction and successful completion','Astra + π₀.₅ · 轨迹修正与任务完成')}</h3><p>{c('π₀.₅ supplies action proposals, while Astra reviews and corrects them. The successful rollouts span releasing a headset caught on the fingers, clearing an occluding arm during mahjong placement, refining wrist position for sorting, correcting an egg grasp, and relocating a misplaced bread slice. These interventions complement the policy’s grasp and finger control. In the mahjong and egg examples, π₀.₅ executes most control steps, while Astra intervenes in three bursts; the mahjong sequence retains the policy’s finger configurations throughout.','π₀.₅ 提供候选动作，Astra 负责审核与修正。成功轨迹涵盖释放挂在手指上的耳机、移开遮挡麻将的手臂、微调分类时的手腕位置、修正鸡蛋抓姿，以及纠正面包的错误放置位置。这些干预与策略的抓握和手指控制形成互补。在麻将与鸡蛋案例中，大多数控制步由 π₀.₅ 执行，Astra 均分三段介入；麻将案例全程保留策略的手指配置。')}</p></div>
  <div className="media-grid">{dexHybridSuccesses.map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div>
  <div className="prose"><h3>{c('Failure modes and control limitations','失败模式与控制局限')}</h3><p>{c('Frequent intervention does not guarantee effective contact control. Constrained hand-pose adjustment, upright-pose assessment, bowl-rim alignment and regrasping after a drop remain failure modes. The egg timeout contains 146 Astra takeover decisions, including 98 with hand edits; the bowl-stacking timeout contains 85 and 15, respectively. The nesting-doll rollout further illustrates repeated grasp and pose adjustments. Together, these cases highlight persistent difficulties in precise contact, grasp recovery and terminal-pose assessment.','频繁介入并不必然带来有效的接触控制。受限空间内的手型调整、直立姿态判断、碗沿对齐，以及物体掉落后的重新抓取仍会导致失败。鸡蛋超时案例包含 146 次 Astra 接管，其中 98 次修改手型；叠碗超时案例分别为 85 次与 15 次。套娃轨迹进一步展示了反复抓取与姿态调整的过程。这些案例共同反映出精细接触、抓握恢复和终态判断方面的持续困难。')}</p></div>
  <div className="media-grid">{dexHybridLimitations.map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div>

  <Conclusion paragraphs={c([
   'Astra + π₀.₅ reaches a mean Score of 61.6, compared with 44.2 for π₀.₅ and 16.6 for Astra, a 17.4-point gain over π₀.₅. The combination improves eight task scores and ties on headphone placement and toy retrieval. The largest gains are in mahjong placement (+40), egg placement (+32) and bottle-and-can sorting (+28). Bread insertion reaches 28 versus 10, nesting-doll arrangement 24 versus 16, and bowl stacking 52 versus 46.',
   'The combination links scene-level correction with a policy that supplies grasp and finger control. Successful interventions address occlusion, release and placement errors; the failure cases show that repeated corrections can still leave contact geometry or object pose unresolved. Stable grasping, recovery after a drop and precise terminal placement remain central challenges.'
  ],[
   'Astra + π₀.₅ 的平均 Score 为 61.6，π₀.₅ 为 44.2，Astra 为 16.6，组合方法比 π₀.₅ 平均高 17.4 分。十项任务中，八项得分提升，耳机放置和玩具取出两项持平。提升最大的是麻将放置（+40 分）、鸡蛋放置（+32 分）和瓶罐分类（+28 分）。面包插入为 28 对 10 分，套娃排列为 24 对 16 分，叠碗为 52 对 46 分。',
   '组合方法将场景级修正与策略的抓握、手指控制结合。成功干预能够处理遮挡、释放和放置错误；失败案例则表明，反复修正仍可能无法建立合适的接触关系或物体姿态。稳定抓握、掉落后的恢复与精确终态放置仍是主要挑战。'
  ])}/>
  <div className="prose"><h3>{c('Matched rollout comparisons','同场景轨迹对照')}</h3><p>{c('The gallery contains 72 rollouts across eight tasks, with three matched seeds per task and one recording each for π₀.₅, Astra and Astra + π₀.₅. Videos are grouped by task and seed for side-by-side inspection of grasping, placement and recovery. π₀.₅ and Astra recordings replay the recorded state trajectories; hybrid recordings also show policy proposals and Astra interventions.','视频库收录八项任务的 72 条轨迹，每项任务选取三个相同 seed 的用例，分别展示 π₀.₅、Astra 和 Astra + π₀.₅。视频按任务与 seed 分组并排呈现，便于比较抓取、放置与恢复过程。π₀.₅ 和 Astra 视频重放已记录的状态轨迹；组合策略视频同时展示策略提议与 Astra 干预。')}</p></div>
  <div className="sec-links"><a href={viewHref('gallery',language,{setting:'dexhand-manipulation',level:'s1',q:'dex-s1-0920'})}>{c('Eight tasks · three-method comparisons ↗','八项任务 · 三种方法配对对照 ↗')}</a><a href="joint-data/dexterous-scores.csv" download>{c('All task scores and instructions · CSV ↓','全部任务得分与指令 · CSV ↓')}</a></div>
 </Section>;
}
DexterousManipulation.meta={id:'dexterous-manipulation',title:{en:'Dexterous Manipulation',zh:'灵巧操作'}};
