import React,{useState} from 'react';
import {Cite} from '../references.jsx';
import results from '../data/results.json';
import {humanoidBenchVideos} from '../data/humanoidbench.js';
import {humanoidSupplement} from '../data/humanoid-supplement.js';
import {useCopy} from '../i18n.jsx';
import {Section,Figure,Bars,Note,Details,DataTable,Toggle,Setup,Conclusion,Stats,number} from '../ui.jsx';
import {MediaCard} from '../media.jsx';

const comparisons=['Maze','Reach','Push','Crawl'].map(name=>results.humanoid.find(r=>r.task===name));
const publishedMethods=[['DreamerV3','dreamerv3_h1hand','#5a6280'],['TD-MPC2','tdmpc2_h1hand','#4b5370'],['SAC','sac_h1hand','#3f4659']];
const published=(r,key)=>Number(r[key].split('±')[0].trim().replace('−','-'));
const returnMax=r=>Math.max(r.mean,r.threshold,...publishedMethods.map(([,key])=>published(r,key)))*1.1;
// Tasks where the combined Astra + Humanoid-GPT result is above all published H1 references.
const leads=r=>publishedMethods.every(([,key])=>r.mean>published(r,key));
const leadCount=results.humanoid.filter(leads).length,thresholdCount=results.humanoid.filter(r=>r.threshold_met).length;
export function Humanoid(){
  const c=useCopy(),[category,setCategory]=useState('all');
  const filtered=results.humanoid.filter(r=>category==='all'||r.category===category);
  return <Section id="humanoid" index={c('S2 / HUMANOID','S2 / 人形机器人')} title="HumanoidBench" subtitle={c('Unitree G1 · 30 tasks · frozen Humanoid-GPT skills','Unitree G1 · 30 项任务 · 冻结的 Humanoid-GPT 技能')}>
    <Setup methods={[
   ['Astra + Humanoid-GPT',c('Task-camera RGB + simulator state + history → Astra chooses walking or whole-body commands and an execution horizon → frozen Humanoid-GPT policy at 50 Hz → joint PD at 500 Hz.','任务相机 RGB + 仿真状态 + 历史 → Astra 选择行走或全身指令及执行时长 → 50 Hz 冻结 Humanoid-GPT 策略 → 500 Hz 关节 PD。')],
   ['DreamerV3 / TD-MPC2 / SAC',c('Published H1 policy returns provide additional context using their own robot, observations and training protocols.','公开 H1 策略回报作为补充参考，沿用各自机器人、观测与训练协议。')]
  ]}><p>{c('We evaluate all 30 executable G1 HumanoidBench tasks, covering standing, walking, running, maze traversal and reaching, as well as contact-rich tasks such as opening a door, pushing, lifting and placing objects. Each task runs on two held-out seeds, 60 episodes in total. For Run, Crawl and Stair, Astra’s commands are rendered as five-point reference trajectories for the same tracker. Skills and controller code are frozen before evaluation, and trajectories are checked by torque replay. The metric is native cumulative return with a task-specific threshold. Astra issues high-level commands throughout; simulation pauses during reasoning.','评测 HumanoidBench 中全部 30 项可运行的 G1 任务，包含站立、行走、跑动、迷宫通过与伸手，以及开门、推物、举物和放置等接触密集任务。每任务在两个留出 seed 上运行，共 60 个 episode。Run、Crawl 与 Stair 中，Astra 的指令被渲染为同一 tracker 执行的五点参考轨迹。评测前冻结技能与控制器代码，并以力矩回放核验轨迹。指标为原生累计回报，使用各任务自己的阈值。Astra 持续发出高层指令，推理期间仿真暂停。')}<Cite ids={["humanoidbench","humanoidgpt"]}/></p></Setup>

    <Figure title={c('Selected task returns','代表任务回报')} subtitle={c('Native cumulative return · higher is better','原生累计回报 · 越高越好')} caption={<>{c('Astra + Humanoid-GPT runs on Unitree G1; bars show its mean return. DreamerV3, TD-MPC2 and SAC are published H1 mean returns from HumanoidBench Table V, using their respective observations and training protocols. Each task has its own return scale; dashed marks show its native return threshold.','Astra + Humanoid-GPT 使用 Unitree G1，条形为其平均回报。DreamerV3、TD-MPC2 与 SAC 为 HumanoidBench Table V 中公开的 H1 平均回报，使用各自的观测与训练协议。各任务使用自己的回报尺度，虚线表示原生回报阈值。')}<Cite ids={['humanoidbench','dreamerv3','tdmpc2','sac']}/></>}>
      <div className="charts-2">{comparisons.map(r=><div key={r.task}><div className="chart-title"><h4>{r.task}</h4><span>{c('Threshold ','阈值 ')+number(r.threshold)}</span></div><Bars max={returnMax(r)} unit="" decimals={1} threshold={r.threshold} rows={[{label:'Astra + Humanoid-GPT · G1',method:'hybrid',value:r.mean},...publishedMethods.map(([label,key,color])=>({label:label+' · H1',value:published(r,key),color}))]}/></div>)}</div>
    </Figure>
    <Stats items={[{value:String(leadCount),unit:'/ 30',label:c('tasks where the combined Astra + Humanoid-GPT result is above every published H1 reference','Astra + Humanoid-GPT 组合结果高于全部公开 H1 参考的任务数')},{value:String(thresholdCount),unit:'/ 30',label:c('tasks whose mean return reaches the native threshold','平均回报达到原生阈值的任务数')}]}/>
    <Note>{c('The combined Astra + Humanoid-GPT result is above all three published H1 references on Stand, Walk, Run, Maze, Hurdle, Crawl, Push, Reach, Bookshelf Hard, Cabinet, Balance Hard, Stair and Room. Stand, Walk, Maze, Crawl, Push and Sit Simple reach their native thresholds; Reach crosses its threshold on one seed only. Published references use H1 under their own protocols, so the comparison is indicative rather than matched.','Astra + Humanoid-GPT 组合结果在 Stand、Walk、Run、Maze、Hurdle、Crawl、Push、Reach、Bookshelf Hard、Cabinet、Balance Hard、Stair 和 Room 上高于全部三个公开 H1 参考。Stand、Walk、Maze、Crawl、Push 与 Sit Simple 达到原生阈值；Reach 仅一个 seed 达标。公开参考使用 H1 及各自协议，该比较仅供参考，并非同条件对照。')}</Note>
    <div className="prose"><h3>{c('Task-level command selection','任务层面的指令选择')}</h3><p>{c('In Maze, Astra turns at checkpoints to make progress through the route. In Reach, it repositions the body before reaching; the stronger seed achieves a 4.1 cm hand-to-target error. Walk (848.7) and Run (642.1) gain from gradual starts, steady cruising and gentle heading feedback rather than higher speed commands; Run still ends below its 700 threshold. Pole combines heading and speed commands and also stays below threshold.','在 Maze 中，Astra 在检查点转向，推进路线进度。在 Reach 中，它先调整身体位置再伸手，较强的 seed 达到 4.1 cm 的手部目标误差。Walk（848.7）与 Run（642.1）的提升来自渐进起步、稳定巡航和轻柔的航向反馈，而非更高的速度指令；Run 仍低于 700 的阈值。Pole 顺序组合朝向与速度指令，同样未达阈值。')}</p></div>
    <div className="prose"><h3>{c('Performance on contact-rich tasks','接触密集任务中的表现')}</h3><p>{c('Push reaches 877.3 on both held-out seeds, above its 700 threshold: with a calibrated stance and a recorded contact fragment in the skill, Astra pushes the box into the native success region. Crawl completes the full 1,000 steps as low, crouched bipedal motion (971.9). Stair improves to 272.5 but one seed falls at step 970 and the other ends displaced backwards, far below threshold. Door never completes the opening-and-passage sequence; Cube and Window drop their objects early. Limited waist/wrist mapping and largely passive fingers restrict the available skills.','Push 在两个留出 seed 上均达到 877.3，超过 700 的阈值：技能中加入校准后的站位与记录的接触片段后，Astra 将箱子推入原生成功区域。Crawl 以低位俯身的双足运动跑满 1,000 步（971.9）。Stair 提升到 272.5，但一个 seed 在第 970 步跌倒，另一个结束时向后位移，仍远低于阈值。Door 始终未完成开门并通过的完整序列；Cube 和 Window 在早期掉落物体。腰部 / 腕部映射受限及大部分被动手指限制了可执行技能。')}</p></div>
    <div className="media-grid is-three">{humanoidBenchVideos.map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div>
    <Details title={c('All 30 task returns and published references','全部 30 项任务回报与公开参考')}>
      <p>{c('One episode on each of two held-out seeds for every executable G1 task; 60 episodes in total. Skills and controller code are frozen. All trajectories reach native termination or the time limit and pass torque-replay verification. Physics pauses during Astra reasoning. DreamerV3, TD-MPC2 and SAC are published H1 mean returns from HumanoidBench Table V, obtained with their own observations, training budgets and seeds.','每个可运行的 G1 任务在两个留出 seed 上各评测一次，共 60 个 episode。技能与控制器代码冻结；所有轨迹达到原生终止条件或时间上限，并通过力矩回放验证。Astra 推理期间物理暂停。DreamerV3、TD-MPC2 与 SAC 为 HumanoidBench Table V 中公开的 H1 平均回报，使用各自的观测、训练预算与 seed。')}</p>
      <Toggle label={c('Task category','任务类别')} options={[['all',c('All tasks','全部')],['loc',c('Locomotion','运动')],['man',c('Manipulation','操作')]]} value={category} onChange={setCategory}/>
      <DataTable className="table-wide" caption={c('Mean cumulative return per task. Orange: the combined S2 result is above all three published H1 references. ✓: mean return reaches the native threshold.','各任务平均累计回报。橙色：组合 S2 结果高于全部三个公开 H1 参考；✓：平均回报达到原生阈值。')} headers={[c('Task','任务'),c('Category','类别'),c('Threshold','阈值'),'Astra + Humanoid-GPT · G1','DreamerV3 · H1','TD-MPC2 · H1','SAC · H1']} rows={filtered.map(r=>[r.task,r.category==='loc'?c('Locomotion','运动'):c('Manipulation','操作'),number(r.threshold),<span className={leads(r)?'is-lead':undefined}>{number(r.mean,1)}{r.threshold_met&&<i className="is-met" aria-label={c('reaches threshold','达到阈值')}> ✓</i>}</span>,...publishedMethods.map(([,key])=>number(published(r,key),1))])}/>
      <p className="note">{c('Slide averages 141.1 return: one seed makes little forward progress, and the other ends in a fall.','Slide 平均回报为 141.1：一个 seed 前进很少，另一个因跌倒结束。')}</p>
    </Details>
    <Details title={c('Supplementary humanoid demonstrations','补充人形机器人演示')}><p>{c('Three additional demonstrations of humanoid reaching and interaction, outside the HumanoidBench evaluation.','三段 HumanoidBench 评测之外的人形机器人伸手与交互补充演示。')}</p><div className="media-grid is-three">{humanoidSupplement.filter(r=>r.domain==='humanoid').map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div></Details>
    <Conclusion paragraphs={c(["The Astra + Humanoid-GPT S2 system is higher than all three published H1 references on 13 of 30 task comparisons, and reaches the native mean-return threshold on six: Stand, Walk, Maze, Crawl, Push and Sit Simple. The Maze mean is 1,358.8 against a threshold of 1,200 and a best published 272.3; Reach averages 11,430.2 against 12,000, with one seed above threshold. Astra selects movement directions, changes heading at checkpoints and repositions the body before reaching, while Humanoid-GPT carries out the motor behavior.","Contact-rich manipulation remains difficult for the frozen skill set. Push succeeds once the skill carries a calibrated contact fragment, but Door, Cube and Window still illustrate failures to sustain contact, retain an object or complete the interaction sequence. The result therefore supports a layered interpretation: Astra supplies S2 command selection, while the quality and coverage of Humanoid-GPT’s motor skills shape which tasks the combined system can finish."],["Astra + Humanoid-GPT 这一 S2 组合系统在 30 项任务比较中有 13 项高于全部三个公开 H1 参考，6 项达到原生阈值：Stand、Walk、Maze、Crawl、Push 和 Sit Simple。Maze 的平均回报为 1,358.8，阈值为 1,200，最佳公开基线为 272.3；Reach 为 11,430.2，阈值为 12,000，其中一个 seed 达标。Astra 选择运动方向、在检查点改变朝向，并在伸手前重新调整身体位置，Humanoid-GPT 则执行底层运动。","冻结技能集在接触密集操作上仍有困难。Push 在技能加入校准接触片段后得以成功，但 Door、Cube 与 Window 仍展现了维持接触、保持物体和完成交互序列方面的失败。因此，这些结果应理解为分层架构的表现：Astra 负责 S2 指令选择，Humanoid-GPT 运动技能的质量与覆盖范围则影响组合系统能完成哪些任务。"])}/>
  <div className="sec-links"><a href="joint-data/humanoid.csv" download>{c('All task data CSV ↓','全部任务数据 CSV ↓')}</a></div>
  </Section>;
}
Humanoid.meta={id:'humanoid',title:{en:'HumanoidBench',zh:'HumanoidBench'}};
