import React,{useState} from 'react';
import {Cite} from '../references.jsx';
import {useCopy} from '../i18n.jsx';
import {Section,Figure,Bars,Toggle,Details,DataTable,Note,Setup,Conclusion,number} from '../ui.jsx';
import {MediaCard,ImageFigure} from '../media.jsx';
import {groups,actionSources,tasks,taskGroups,controlMethods,mobileRoot,mobileClip} from '../data/mobile.js';

export function MobileManipulation(){
 const c=useCopy(),[group,setGroup]=useState('all');
 const displayed=tasks.filter(r=>group==='all'||r[1]===group);
 return <Section id="mobile-manipulation" index={c('S1 ↔ S2 / MOBILE MANIPULATION','S1 ↔ S2 / 移动操作')} title={c('Mobile Manipulation','移动操作')} subtitle={c('RoboCasa365 · 15 tasks × 5 seeds × 3 conditions','RoboCasa365 · 15 个任务 × 5 个种子 × 3 种条件')}>
  <Setup methods={[
   ['π₀.₅',c('Original instruction + observation → frozen π₀.₅ checkpoint → robot controller.','原始指令 + 观测 → 冻结 π₀.₅ 检查点 → 机器人控制器。')],
   ['Astra',c('Left/right/wrist RGB + proprioception → Astra → numerical end-effector, gripper, base and torso commands → controller.','左／右／腕部 RGB + 本体状态 → Astra → 末端、夹爪、底盘和躯干数值指令 → 控制器。')],
   ['Astra + π₀.₅',c('Astra can accept proposals from the same π₀.₅, rewrite its language subgoal or author replacement actions. Usually 20 control steps execute before the next observation.','Astra 可接受同一 π₀.₅ 的候选动作、重写其语言子目标，或自行生成替代动作；通常每次观测间执行 20 个控制步。')]
  ]}><p>{c('Fifteen RoboCasa365 kitchen tasks test atomic actions and longer composite tasks. Each condition uses five seeds per task: 75 episodes, split equally among atomic seen, composite seen and composite unseen tasks relative to policy training. Task, seed, initial state, controller and success test are shared; the recorded harness versions differ. Astra receives images and proprioception rather than object poses or intermediate rewards.','RoboCasa365 的十五项厨房任务检验原子动作与较长的复合任务。每种条件、每任务五个 seed，共 75 个 episode，等分为相对策略训练集的已见原子、已见复合、未见复合任务。各条件共享任务、seed、初态、控制器与成功判据，记录的执行框架版本有差异。Astra 接收图像与本体状态，不接收物体位姿或中间奖励。')}<Cite ids={['robocasa365','robocasa']}/></p><p>{c('The primary metric is native task success: a trial is successful when RoboCasa’s task-specific goal conditions are satisfied within the action horizon. We report success rate overall and for each group, with per-task counts out of five. The three groups contain the following tasks.','主指标为 RoboCasa 原生任务成功率，按各任务在动作时限内的目标条件判断；同时给出总体、分组成功率与每任务五次运行的成功数。三组任务分别为：')}</p><ul>
   <li>{c('Atomic seen: CoffeeSetupMug, OpenDrawer, OpenStandMixerHead, PickPlaceDrawerToCounter and PickPlaceSinkToCounter.','已见原子任务：咖啡杯准备、打开抽屉、抬起厨师机机头、抽屉到台面取放、水槽到台面取放。')}</li>
   <li>{c('Composite seen: DeliverStraw, KettleBoiling, PackIdenticalLunches, SearingMeat and WashLettuce.','已见复合任务：递送吸管、烧水、打包两份相同午餐、煎肉、清洗生菜。')}</li>
   <li>{c('Composite unseen: BreadSelection, GatherTableware, HeatKebabSandwich, MakeIceLemonade and RecycleBottlesByType.','未见复合任务：选择面包、收集餐具、加热烤肉三明治、制作冰柠檬水、按材质分类回收瓶子。')}</li>
  </ul></Setup>

  <Figure title={c('Success by task group','各任务组成功率')} subtitle={c('Labels: successes / episodes · bars: success rate','标签：成功数 / episode 数 · 条形：成功率')} caption={c('Seen and unseen refer to task membership in the π₀.₅ training set. Each group contains five tasks with five seeds per task, using kitchen layouts from the pretrain split.','已见与未见按任务是否属于 π₀.₅ 训练集划分。每组包含五个任务、每任务五个 seed，厨房布局来自 pretrain 划分。')}>
   <div className="charts-2">{groups.map(r=><div key={r.group}><div className="chart-title"><h4>{c(...taskGroups[r.group])}</h4><span>n = {r.n}</span></div><Bars rows={controlMethods.map(([key,label,method])=>({label,method,value:100*r[key]/r.n,display:r[key]+'/'+r.n+' · '+number(100*r[key]/r.n,1)+'%'}))}/></div>)}</div>
  </Figure>
  <p>{c('Astra + π₀.₅ completes 13/25 atomic seen episodes, compared with 7/25 for Astra. Astra is stronger on composite unseen tasks: 14/25 versus 9/25 for Astra + π₀.₅. Both Astra conditions score 0/5 on CoffeeSetupMug and WashLettuce, where π₀.₅ scores 3/5 and 2/5. Astra completes all five RecycleBottlesByType episodes.','在已见原子任务上，Astra + π₀.₅ 为 13/25，高于 Astra 的 7/25；在未见复合任务上，Astra 为 14/25，高于 Astra + π₀.₅ 的 9/25。CoffeeSetupMug 和 WashLettuce 中两种 Astra 条件均为 0/5，而 π₀.₅ 分别为 3/5 和 2/5。Astra 完成了全部五个 RecycleBottlesByType episode。')}</p>

  <div className="media-grid">{['robocasa-KettleBoiling-00','robocasa-RecycleBottlesByType-01','robocasa-CoffeeSetupMug-03','robocasa-PickPlaceDrawerToCounter-04'].map(id=><MediaCard key={id} clip={{...mobileClip(id),initialView:'comparison'}}/>)}</div>
  <Note>{c('These cases open in the three-condition comparison. Videos play at 4× simulator time, omit model waiting, and hold terminal frames after a condition finishes. Auxiliary views may retain the latest observation. The examples show each controller’s behavior from matched initial states.','这些案例默认打开三组对照。视频按仿真时间 4 倍速播放，省略模型等待；某条件结束后保持末帧，辅助视角可能保留最近观测。这些案例展示各控制器从配对初态出发的执行过程。')}</Note>
  <p>{c('In Astra + π₀.₅, the policy supplies 72,095 executed steps and Astra supplies 58,454, or 44.8% of the total. Astra rewrites language subgoals in 66 of 75 episodes. Its role therefore includes both choosing how to condition the policy and correcting the resulting actions.','Astra + π₀.₅ 中，策略提供 72,095 个实际执行步，Astra 提供 58,454 步，占总步数的 44.8%。Astra 在 75 次运行中的 66 次重写了语言子目标，既调整策略接收的任务描述，也修正输出动作。')}</p>
  <div className="prose"><h4>{c('Per-task success counts','逐任务成功数')}</h4>
   <div className="chart-controls"><Toggle label={c('Task group','任务组')} options={Object.entries(taskGroups).map(([key,labels])=>[key,c(...labels)])} value={group} onChange={setGroup}/><span>{c('5 seeds per task','每个任务 5 个种子')}</span></div>
   <DataTable className="table-heat" caption={c('Task-level successes · each cell is out of five','任务成功数 · 每格共五个种子')} headers={[c('Task','任务'),c('Group','任务组'),'π₀.₅','Astra','Astra + π₀.₅']} rows={displayed.map(([task,key,...values])=>[task,c(...taskGroups[key]),...values.map((v,i)=><span key={i} className="heat-cell" style={{background:['#161826','#1c2340','#233064','#2c418f','#3b5bd9','#5b7cff'][v],color:v>=3?'#fff':'#c3c7d6'}}>{v}/5</span>)])}/>
  </div>
  <Details title={c('Control interface and action accounting','控制接口与动作统计')}>
   <p>{c('Astra observes left, right and wrist RGB images plus robot proprioception. Object poses, the full simulator state and intermediate task rewards are withheld. Astra emits numerical end-effector, gripper, base and torso commands. Astra + π₀.₅ can accept frozen π₀.₅ proposals, rewrite their language subgoal or author its own actions. Standalone π₀.₅ uses the same checkpoint with the original instruction. Normally 20 control steps execute between observations.','Astra 接收左、右、腕部 RGB 图像和机器人本体状态，不接收物体位姿、完整仿真状态或中间任务奖励。Astra 输出末端、夹爪、底盘和躯干的数值指令；Astra + π₀.₅可接受冻结 π₀.₅ 候选、重写其语言子目标，或自行生成动作。π₀.₅ 使用同一检查点与原始任务指令。通常每次观测之间执行 20 个控制步。')}</p>
   <DataTable headers={[c('Action accounting · Astra + π₀.₅','动作统计 · Astra + π₀.₅'),c('Count','数量')]} rows={[[c('Executed policy steps','执行的策略步数'),number(actionSources.accepted_policy_steps)],[c('Executed Astra-authored steps','执行的 Astra 生成步数'),number(actionSources.astra_authored_steps)],[c('Policy proposals / accepted proposals','策略候选 / 接受候选'),number(actionSources.policy_proposals)+' / '+number(actionSources.accepted_proposals)],[c('Astra-authored segments','Astra 生成片段'),number(actionSources.astra_authored_segments)],[c('Proposals with rewritten instruction','指令重写后的候选'),number(actionSources.proposals_with_rewritten_instruction)]]}/>
   <p>{c('The comparison covers 15 tasks with five seeds each. Conditions share task, seed, physical initial state, controller, horizon and success test. Context compaction, prefetching and feedback guards evolved during the experiment; each condition includes a different mix of harness versions. Results summarize these evaluated system configurations.','对照覆盖十五项任务、每任务五个 seed。各条件共享任务、seed、物理初始状态、控制器、时长上限和成功测试。实验中上下文压缩、预取与反馈保护机制逐步更新，各条件包含的执行框架版本组合有所不同；结果汇总这些受测系统配置的表现。')}</p>
   <ImageFigure src="media/joint/robocasa-cases-astra.png" alt={c('Matched initial and terminal scenes in three RoboCasa control conditions','三种 RoboCasa 控制条件下的配对初始与终止画面')} caption={c('Matched initial and terminal views for the three control conditions. Episode outcomes use the benchmark’s success test.','三种控制条件的配对初始与终止画面；episode 结果按基准成功判据统计。')}/>
  </Details>
  <Conclusion paragraphs={c(["Across the 75 task–seed pairs, π₀.₅, Astra and Astra + π₀.₅ succeed in 17, 25 and 29 episodes, respectively. The benefit of combining the models depends on the task group: Astra + π₀.₅ is stronger on atomic seen tasks, while Astra is stronger on composite unseen tasks.","The case results show complementary strengths. π₀.₅ completes coffee preparation and lettuce washing episodes missed by both Astra configurations; Astra completes all five bottle-recycling episodes. Astra + π₀.₅ has the highest overall success rate in this evaluation, while π₀.₅ retains an advantage on some familiar kitchen interactions."],["在 75 组任务与 seed 配对中，π₀.₅、Astra 和 Astra + π₀.₅ 分别成功 17、25 和 29 次。组合方法的收益随任务组变化：Astra + π₀.₅ 在已见原子任务上更好，Astra 在未见复合任务上更好。","逐任务结果体现了不同方法的互补性。π₀.₅ 完成了两种 Astra 配置均未完成的咖啡准备与生菜清洗案例；Astra 则完成了全部五次瓶子分类回收。Astra + π₀.₅ 在这组评测中取得最高总体成功率，π₀.₅ 在部分熟悉的厨房交互上仍保有优势。"])}/>
  <div className="sec-links"><a href={mobileRoot+'data/robocasa-paired.csv'} download>{c('75 three-condition pairs · CSV ↓','75 组三条件配对记录 · CSV ↓')}</a><a href={mobileRoot+'data/robocasa-tasks.csv'} download>{c('Task results · CSV ↓','任务结果 · CSV ↓')}</a></div>
 </Section>;
}
MobileManipulation.meta={id:'mobile-manipulation',title:{en:'Mobile Manipulation',zh:'移动操作'}};
