import React from 'react';
import {Cite} from '../references.jsx';
import {useCopy} from '../i18n.jsx';
import {Section,Figure,Bars,Details,DataTable,Setup,Conclusion,number} from '../ui.jsx';
import {MediaCard,ImageFigure} from '../media.jsx';
import {trackingPair,trackingPolicies,s0Clip} from '../data/s0.js';
export function MotionTracking(){
 const c=useCopy();
 return <Section id="motion-tracking" index={c('S0 / DIRECT JOINT CONTROL','S0 / 直接关节控制')} title={c('Motion Tracking','运动追踪')} subtitle="Unitree G1 · LAFAN1 · MuJoCo / mjlab">
  <Setup methods={[
   ['Astra · a01 / a02',c('State + short reference horizon + action history → Astra and its textual control skill → 29 joint PD targets → four 5 ms substeps. a02 revises a01’s skill; model weights stay fixed.','状态 + 短时参考窗口 + 动作历史 → Astra 及文本控制技能 → 29 维关节 PD 目标 → 四个 5 ms 子步。a02 修订 a01 的技能，模型权重不变。')],
   ['ScaleTrack',c('Reference motion + robot feedback → trained tracking policy → joint controller. It provides the learned motor-control reference for the same motion.','参考动作 + 机器人反馈 → 训练后的追踪策略 → 关节控制器，作为同一参考动作的 learned policy baseline。')]
  ]}><p>{c('G1 tracks LAFAN1 walking motions in MuJoCo / mjlab. The main comparison uses the ten-second walk2_subject3 reference and paired Astra skill versions a01 and a02 under the same reset and physics, with simulator diagnostics allowed. Each plotted condition is one rollout of this reference. We measure time to native termination and mean body-position error over the common first 0.8 s. Both versions permit the same simulator assistance, including up to four copied-simulation comparisons (eight trajectories, 0.48 s total). Simulation and reference phase pause during inference.','G1 在 MuJoCo / mjlab 中追踪 LAFAN1 行走动作。主对照使用十秒 walk2_subject3 参考与配对的 Astra 技能版本 a01 与 a02，重置和物理相同，允许仿真诊断。图中每个条件对应这一参考动作的一条 rollout。指标为原生终止前的存活时间，以及共同前 0.8 秒内的平均身体位置误差。两版均允许相同的仿真辅助，包括最多四次复制仿真对照（八条轨迹，累计 0.48 秒）。推理期间仿真与参考相位暂停。')}<Cite ids={["g1","lafan1","mujoco","mjlab"]}/></p></Setup>

  <Figure title={c('Tracking a walking reference','追踪行走参考动作')} subtitle="walk2_subject3" caption={c('Astra a01 and a02 are two successive versions of the textual control skill. Both use the same reset, physics and permitted simulator diagnostics. ScaleTrack is the separate trained-policy reference. Error averages body-position distances over the same first 0.8 s; survival ends at the first native termination, which can precede a visible fall.','Astra a01 与 a02 是文本控制技能的两个连续版本；二者使用相同重置、物理与允许的仿真诊断。ScaleTrack 为独立的训练策略基线。误差均取前 0.8 秒身体位置距离的均值；存活截至首次原生终止，可早于可见跌倒。')}>
   <div className="charts-2">{[['survival',c('Survival · seconds ↑','存活 · 秒 ↑'),10,2],['error',c('Initial body-position error · cm ↓','初始身体位置误差 · cm ↓'),12,2]].map(([key,title,max,decimals])=><div key={key}><div className="chart-title"><h4>{title}</h4></div><Bars unit={key==='survival'?' s':' cm'} max={max} decimals={decimals} rows={trackingPair.map(r=>({label:r.label,value:r[key],method:r.method,color:r.color}))}/></div>)}</div>
  </Figure>
  <div className="prose"><h3>{c('From holding a pose to transferring support','从保持姿态到转移支撑')}</h3><p>{c('Astra’s textual skill was revised through rollout inspection and hypotheses about balance, swing clearance, landing and support transfer, with model weights fixed. Development rollouts show brief stable phases followed by tracking-error termination. In the paired comparison, a02 terminates earlier than a01 and has higher error over the fixed window.','Astra 的文本技能通过轨迹复盘以及平衡、摆腿净空、落足和支撑转移假设迭代，模型权重固定。开发轨迹中出现过短暂稳定阶段，随后因追踪误差触发终止。在配对对照中，a02 比 a01 更早终止，固定窗口内的误差也更高。')}</p></div>
  <div className="media-grid"><MediaCard clip={s0Clip('s0-t1')}/><MediaCard clip={s0Clip('s0-t3')}/></div>
  <Details title={c('Development history and trained-policy references','开发历程与训练策略参考')}><ImageFigure src="media/s0/tracking-history.png" alt={c('Twenty-four completed tracking attempts: survival and fixed-window error against cumulative project tokens','24 次已结束追踪尝试：存活与固定窗口误差随项目累计 token 的变化')} caption={c('24 ended attempts on walk2_subject3; two unfinished records are excluded. The horizontal axis uses cumulative project API tokens, including cached input once and work on other motions. Protocols and assistance changed during development; these connected observations describe the history.','walk2_subject3 的 24 次已结束尝试，排除两条未结束记录。横轴为项目累计 API tokens，缓存输入计一次，并包含其他动作上的工作。开发中协议和辅助方式有变化；连线用于呈现历史记录。')}/><DataTable caption={c('Trained ScaleTrack · each reference completes 10 s','训练后的 ScaleTrack · 各参考均完成 10 秒')} headers={[c('Motion','动作'),c('First 0.8 s error · cm','前 0.8 秒误差 · cm'),c('Full 10 s error · cm','完整 10 秒误差 · cm')]} rows={trackingPolicies.map(([name,a,b])=>[name,number(a,2),number(b,2)])}/><p>{c('Development and evaluation across the reference motions total approximately 1.092 billion API tokens in the project counter.','不同参考动作的开发与评测在项目计数器中合计约 10.92 亿 API tokens。')}</p></Details>
  <Details title={c('Observation, execution and evaluation protocol','观测、执行与评测协议')}><DataTable headers={[c('Input','输入'),c('Shape','形状'),c('Content','内容')]} rows={[[c('Robot state','机器人状态'),'3 × 64',c('Gravity, angular velocity, joint positions and velocities','重力、角速度、关节位置与速度')],[c('Reference','参考'),'6 × 253',c('14-body targets and pose errors, 0–100 ms horizon','14 部位目标与位姿误差，0–100 ms 窗口')],[c('Action history','动作历史'),'3 × 29',c('Previous normalized actions','历史归一化动作')]]}/><p>{c('One fresh target in radians advances four 5 ms PD substeps. Simulation and reference phase pause during inference. Earlier trials used multi-row packets; some trials additionally used expanded state and copied-simulation comparisons. Native failure includes a tracked body exceeding 0.5 m global position error and the original anchor-height/orientation conditions. Development motions became seen data when their outcomes informed revisions.','每个新目标以弧度表示，执行四个 5 ms PD 子步。推理期间仿真与参考相位暂停。早期尝试使用多行指令，部分实验额外使用扩展状态和复制仿真对照。原生失败包括任一追踪部位全局位置误差超过 0.5 m，以及原有锚点高度／朝向条件。动作结果一旦用于修订，即属于已见开发数据。')}</p><div className="media-grid"><MediaCard clip={s0Clip('s0-t2')}/><MediaCard clip={s0Clip('s0-t4')}/></div></Details>
  <Conclusion paragraphs={c(["ScaleTrack completes the ten-second walking reference. Astra a01 and a02 terminate at 1.04 s and 0.96 s, with initial body-position errors of 10.28 cm and 10.83 cm, compared with 4.45 cm for ScaleTrack. The a02 revision does not improve either metric in this paired comparison.","The development videos include short upright phases and corrective steps, followed by growing tracking error or support drift. Producing joint targets at every control interval still requires coordinated balance, landing and support transfer. For this reference, the learned tracker maintains that coordination substantially longer than the evaluated Astra skills."],["ScaleTrack 完成了十秒行走参考。Astra a01 与 a02 分别在 1.04 秒和 0.96 秒触发终止，初始身体位置误差为 10.28 cm 和 10.83 cm，ScaleTrack 为 4.45 cm；这一配对实验中的文本技能修订未改善两项指标。","开发录像中可见短暂站稳与修正步伐，随后出现追踪误差增大或支撑漂移。逐控制周期生成关节目标，需要持续协调平衡、落足和支撑转移。在这一参考动作上，learned tracker 比受测 Astra 技能维持了更长时间的协调运动。"])}/>
  <div className="sec-links"><a href="joint-data/s0-tracking-attempts.csv" download>{c('Attempt history · CSV ↓','逐次记录 · CSV ↓')}</a><a href="joint-data/s0-tracking-policy-baselines.csv" download>{c('Trained-policy references · CSV ↓','训练策略基线 · CSV ↓')}</a></div>
 </Section>;
}
MotionTracking.meta={id:'motion-tracking',title:{en:'Motion Tracking',zh:'运动追踪'}};
