import React from 'react';
import {Cite} from '../references.jsx';
import results from '../data/results.json';
import {useCopy} from '../i18n.jsx';
import {Section,Figure,Bars,Details,DataTable,Setup,Conclusion,number} from '../ui.jsx';
import {MediaCard,ImageFigure} from '../media.jsx';
import {locomotionTasks,s0Clip} from '../data/s0.js';
export function MotorControl(){
 const c=useCopy();
 return <Section id="motor-control" index={c('S0 / DIRECT JOINT CONTROL','S0 / 直接关节控制')} title={c('Flat-ground Locomotion','平地运动控制')} subtitle={c('Unitree G1 · Isaac Sim · 20 Hz targets / 200 Hz physics','Unitree G1 · Isaac Sim · 20 Hz 目标 / 200 Hz 物理')}>
  <Setup methods={[
   ['Astra',c('Current state + recent observations/actions + task memory → Astra → one 29-joint position target every 50 ms → fixed PD and torque limits → G1.','当前状态 + 近期观测／动作 + 任务记忆 → Astra → 每 50 ms 一个 29 维关节位置目标 → 固定 PD 与力矩限幅 → G1。')],
   [c('Reset and reflection','重置与反思'),c('After failure, Astra records one reflection and resets to the same pose and zero velocity. Standing, walking and turning each maintain a separate memory and one independent attempt sequence.','失败后记录一次反思，并重置为相同姿态与零速度。站立、直行、右转分别维护独立记忆，各进行一条尝试序列。')]
  ]}><p>{c('On Unitree G1 in Isaac Sim, we ask whether Astra can produce low-level targets for standing, straight walking and right turning. Standing must remain stable for 30 s. Walking targets at least 1 m; turning targets −90° ± 10°. Moving tasks begin with 5 s of standing and require alternating steps, limited foot slip and a stable stop. Physics runs at 200 Hz, with 20 Hz target updates.','在 Isaac Sim 的 Unitree G1 上，检验 Astra 能否直接生成站立、直行与右转的底层目标。站立要求稳定保持 30 秒；直行要求至少 1 m，右转要求 −90° ± 10°。运动任务先站立 5 秒，还需满足交替步、足部滑移限制及稳定停止判据。物理频率 200 Hz，目标更新 20 Hz。')}<Cite ids={["isaacsim","g1"]}/></p><p>{c('Each task runs one independent reset-and-reflect sequence: one standing attempt, nine walking attempts and eleven turning attempts. The last walk and turn are stopped at the resource limit. Metrics are completed survival time, forward displacement or yaw change, and violations of the task’s stability and stepping criteria.','每项任务运行一条独立的重置与反思序列：站立一次、直行九次、右转十一次，最后一条直行与右转在资源预算处停止。指标为完整尝试的存活时间、前向位移或航向变化，以及稳定性与步态判据的违反情况。')}</p></Setup>

  <Figure title={c('Standing, walking and turning','站立、直行与右转')} subtitle={c('Observed progress and task targets','观测进展与任务目标')} caption={c('Each value is the maximum observed within its task sequence, and maxima need not come from the same attempt. Walking requires at least 1 m final forward displacement; turning targets −90° ± 10°. Completion also checks stability, support-foot slip, alternating steps and stopping.','每项数值取对应任务序列中的最大观测值，不同指标的最大值可来自不同尝试。直行要求最终前进至少 1 m；右转目标为 −90° ± 10°。完成任务还需满足稳定性、支撑脚滑移、交替步和停止判据。')}>
   <div className="charts-2"><div><div className="chart-title"><h4>{c('Longest completed survival · s','最长完整存活 · 秒')}</h4></div><Bars max={30} rows={locomotionTasks.map(r=>({label:c(r.en,r.zh),value:r.survival,display:r.survival.toFixed(2)+' s',method:'gpt'}))}/></div><div><div className="chart-title"><h4>{c('Progress relative to task target','相对任务目标的进展')}</h4></div><Bars max={100} rows={[{label:c('Standing','站立'),value:100,display:'30 / 30 s',method:'gpt'},{label:c('Walking','直行'),value:38.3617,display:'0.384 / 1 m',method:'gpt'},{label:c('Right turn','右转'),value:34.6635,display:'31.2 / 90°',method:'gpt'}]}/></div></div>
   <DataTable className="table-wide" caption={c('Task-level totals · one independent attempt sequence per task','任务级合计 · 每项任务各运行一条独立尝试序列')} headers={[c('Task','任务'),c('Completed outcomes','已完成结果'),c('Unfinished at stop','停止时未完成'),c('Returned tokens','已返回 tokens'),c('Billed calls','计费调用')]} rows={locomotionTasks.map(r=>[c(r.en,r.zh),r.task==='stand'?c('1 success','1 次成功'):r.failures+c(' failures',' 次失败'),r.censored,number(r.tokens),number(r.calls)])}/>
  </Figure>
  <div className="media-grid is-three"><MediaCard clip={results.videos.find(r=>r.id==='flat-stand')}/><MediaCard clip={s0Clip('s0-l3')}/><MediaCard clip={s0Clip('s0-l4')}/></div>
  <div className="prose"><h3>{c('Stable standing, limited stepping','稳定站立与有限的迈步能力')}</h3><p>{c('Standing executes 600 PD targets with at most 8.59° tilt and 0.062 m horizontal drift. Across the completed walking attempts, four violate foot-slip limits, three cross the lateral boundary and two exceed tilt limits; violations overlap. The best walk records two valid alternating steps against a requirement of six. Right-turn failures also concentrate on slip, position and tilt.','站立执行 600 个 PD 目标，最大倾角为 8.59°、水平漂移为 0.062 m。完整直行失败中，四次触发脚滑移、三次横向越界、两次倾角超限，原因可重叠。最佳直行记录两个合格交替步，任务要求六个。右转失败也主要涉及滑移、位置和倾角。')}</p></div>
  <Details title={c('All 21 attempts and resource accounting','全部 21 次尝试与资源统计')}><ImageFigure src="media/s0/locomotion-history.png" alt={c('Survival and commanded progress over task-local cumulative tokens','存活与指令进展随任务内累计 token 的变化')} caption={c('Each task starts at zero tokens. Connected points are separate reset attempts; open markers are the final incomplete walk and turn. Those attempts were administratively stopped and are excluded from physical-failure counts.','各任务从零 token 开始。连线连接独立重置的尝试，空心点为最后未完成的直行与右转；这两次因人工停止而删失，不计作物理失败。')}/><p>{c('Each task uses one independent reset-and-reflect sequence. Walking and turning each stop near a 40M-token budget. Returned prompt plus completion usage totals 92,806,457 tokens; reasoning tokens are already included in completion. Every extra 0.05 s of control requires another model request, so survival–token correlations also reflect the interface itself.','每任务运行一条独立的重置—反思序列；直行与右转分别在接近 40M tokens 预算时停止。已返回的输入与输出合计 92,806,457 tokens；推理 tokens 已包含在输出内。每多执行 0.05 秒控制都需新模型请求，因此存活与 token 的相关性也反映接口本身。')}</p><DataTable headers={[c('Task','任务'),c('Admitted PD actions','实际 PD 动作'),c('Reflection calls','反思调用')]} rows={locomotionTasks.map(r=>[c(r.en,r.zh),number(r.actions),r.failures])}/><MediaCard clip={s0Clip('s0-l2')}/></Details>
  <Details title={c('Control interface and completion criteria','控制接口与完成判据')}><p>{c('Astra uses high reasoning and observation-only, stateless requests. Its inputs include robot parameters, current state, the last two observation/action pairs, task-local memory and earlier failures. Each admitted response supplies one finite 29-joint target; fixed PD control and torque limits execute it. A failed episode is followed by one reflection and a reset to the same initial pose and zero velocity. Memory is separate for standing, walking and turning.','Astra 使用 high 推理和仅基于观测的无状态请求。输入包括机器人参数、当前状态、最近两对观测／动作、任务内记忆与此前失败。每次有效响应提供一个有限的 29 维关节目标，由固定 PD 与力矩限幅执行。失败后进行一次反思，再重置为相同初始姿态与零速度；站立、直行、右转分别维护记忆。')}</p><p>{c('Standing lasts 30 s with root height ≥ 0.60 m, tilt ≤ 15°, horizontal drift ≤ 0.10 m, foot drift ≤ 0.05 m, no non-foot contact, low final velocity and dual-foot support. Walking and turning first stand for 5 s, move for 15 s, then stop. Both require six valid alternating steps and stance slip ≤ 0.03 m. Walking also limits lateral error to 0.15 m and heading error to 15°; turning stays within 0.25 m of the origin.','站立持续 30 秒，要求根高度 ≥ 0.60 m、倾角 ≤ 15°、水平漂移 ≤ 0.10 m、足部漂移 ≤ 0.05 m，无非足部接触，结束时低速度且双脚支撑。直行／右转先站立 5 秒，运动 15 秒，再停止；均要求六个合格交替步及支撑脚滑移 ≤ 0.03 m。直行另要求横向误差 ≤ 0.15 m、朝向误差 ≤ 15°；右转保持在起点 0.25 m 范围内。')}</p></Details>
  <Conclusion paragraphs={c(["Astra completes 30 seconds of standing on its first attempt, with 8.59° maximum tilt and 0.062 m horizontal drift. Walking and turning are harder: the longest completed attempts last 7.60 s and 7.15 s, and the largest motion extents are 0.384 m forward and 31.2° clockwise.","The moving tasks require sustained alternating support and a stable stop. The best walking attempt records two valid alternating steps against the requirement of six; failures involve foot slip, lateral drift and tilt. Within these reset-and-reflect sequences, Astra achieves static balance more reliably than the coordinated stepping needed for the full movement targets."],["Astra 首次尝试完成 30 秒站立，最大倾角为 8.59°，水平漂移为 0.062 m。直行与右转更困难：最长完整尝试分别为 7.60 秒和 7.15 秒，最大运动幅度为向前 0.384 m 和顺时针 31.2°。","运动任务还要求持续交替支撑与稳定停止。最佳直行只记录到两个合格交替步，任务要求六个；失败主要涉及足部滑移、横向漂移和倾角超限。在这些重置与反思序列中，Astra 的静态平衡表现优于完成目标运动所需的连续迈步协调。"])}/>
  <div className="sec-links"><a href="joint-data/s0-locomotion-summary.csv" download>{c('Task summary · CSV ↓','任务汇总 · CSV ↓')}</a><a href="joint-data/s0-locomotion-attempts.csv" download>{c('All 21 attempts · CSV ↓','全部 21 次尝试 · CSV ↓')}</a></div>
 </Section>;
}
MotorControl.meta={id:'motor-control',title:{en:'Flat-ground Locomotion',zh:'平地运动控制'}};
