import React from 'react';
import {Cite} from '../references.jsx';
import results from '../data/results.json';
import {humanoidSupplement} from '../data/humanoid-supplement.js';
import {obstacle65DUsage as compute} from '../data/token-usage.js';
import {useCopy} from '../i18n.jsx';
import {Section,Figure,Bars,Note,Details,DataTable,Flow,Setup,Conclusion,Stats,number} from '../ui.jsx';
import {MediaCard} from '../media.jsx';

export function Obstacles(){
  const c=useCopy(),get=id=>results.videos.find(v=>v.id===id);
  return <Section id="obstacles" index={c('S1 / OBSTACLE AVOIDANCE','S1 / 避障')} title={c('Obstacle Avoidance','避障')} subtitle={c('G1 AGX · the same scene, reset, tracker and control interface','G1 AGX · 相同场景、重置、跟踪器与控制接口')}>
    <Setup methods={[
   ['Astra + ScaleBFM',c('Motion history + local height scan + route goal → Astra → 25 × 65D motion reference covering 0.5 s → perceptive ScaleBFM → joint PD. Replan every six control steps.','运动历史 + 局部高度扫描 + 路线目标 → Astra → 覆盖 0.5 秒的 25 × 65D 运动参考 → 感知型 ScaleBFM → 关节 PD，每六个控制步重规划。')],
   ['Passage + ScaleBFM',c('The same input interface → learned Passage planner → the same reference decoder and ScaleBFM tracker → joint PD. Both planners receive a route-goal tape.','相同输入接口 → 训练后的 Passage 规划器 → 相同参考解码器与 ScaleBFM 追踪器 → 关节 PD。两种规划器均获得路线目标序列。')]
  ]}><p>{c('A G1 AGX moves through one fixed open-clutter scene (0089), with the same reset and seed. Control runs at 50 Hz and physics at 500 Hz. The goal tolerance is 0.5 m. We compare Passage with five sequential Astra attempts that share scene memory, recording goal progress, falls, contact and latency. Goal progress is the reduction in distance from the start to the final position; final goal error measures the remaining distance. This sequence measures adaptation in one scene.','G1 AGX 在固定 open-clutter 场景 0089 中运动，使用相同重置和 seed。控制频率为 50 Hz，物理为 500 Hz，到达容差为 0.5 m。比较 Passage 与共享场景记忆的五次连续 Astra 尝试，记录朝目标进展、跌倒、接触和延迟；朝目标进展为初始与最终目标距离之差，最终误差为结束时距目标的距离；该序列用于观察同一场景中的适应过程。')}<Cite ids={["passage","scalebfm"]}/></p></Setup>
    <Figure title={c('One scene · five adaptive attempts','同一场景 · 五次适应尝试')} subtitle={c('Goal progress (m) · larger is better','朝目标的净进展（m）· 越大越好')} caption={c('Five sequential attempts on the same scene, with shared memory and iterative control adjustments. Bars show progress toward the goal in each attempt. Both planners receive a privileged route-goal tape.','同一场景中的五次连续尝试，共享记忆并逐步调整控制。条形展示各次尝试朝目标的进展；两种规划器均获得特权路线目标序列。')}>
      <Bars max={10} unit=" m" decimals={3} rows={results.clutter.map((r,i)=>({label:i===0?'Passage':c('Astra · attempt ','Astra · 尝试 ')+i,method:i===0?'baseline':'gpt',value:r.progress_m,display:number(r.progress_m,3)}))}/>
      <Note>{c('Astra attempt 2 ends 0.024 m farther from the goal than it starts (progress: −0.024 m).','Astra 第 2 次尝试结束时比初始位置距目标更远 0.024 m，净进展为 −0.024 m。')}</Note>
    </Figure>
    <div className="prose"><h3>{c('Adaptation across sequential attempts','连续尝试中的适应过程')}</h3><p>{c('The first attempt moves forward, collides and falls. Attempts 2–4 favor stability but make little progress. By attempt 5, the robot advances 2.598 m without falling or obstacle contact over 30 s of simulation, then stops short of the obstacle; final goal error is 6.519 m. Scene-memory revisions and changes to motion context, phase and amplitude occur together. The remaining challenge is producing continuous references that both clear obstacles and remain executable by the tracker.','首次尝试向前移动后碰撞跌倒；第 2–4 次偏向维持稳定，前进很少。第 5 次在 30 秒仿真时间内无跌倒、无障碍接触地前进 2.598 m，随后在障碍前停下，最终距目标 6.519 m。场景记忆修订与运动参考、相位、幅度调整同期发生。后续难点在于持续生成既满足障碍净空、又能被追踪器可靠执行的参考。')}</p></div>
    <div className="media-grid"><MediaCard clip={get('clutter-passage')}/><MediaCard clip={get('clutter-gpt5')}/></div>
    <div className="prose" id="obstacle-compute"><h3>{c('Compute cost and time accounting','计算开销与时间口径')}</h3>
     <Stats items={[{value:compute.passage_mean_planner_latency_s.toFixed(3),unit:'s',label:c('Passage · mean planner latency','Passage · 平均规划延迟')},{value:compute.astra_mean_turn_latency_s.toFixed(2),unit:'s',label:c('Astra · attempt 5 · mean model-turn latency','Astra · 第 5 次尝试 · 平均模型调用延迟')},{value:compute.astra_max_turn_latency_s.toFixed(2),unit:'s',label:c('Astra · attempt 5 · maximum model-turn latency','Astra · 第 5 次尝试 · 最大模型调用延迟')}]}/>
     <p>{c('The simulator pauses while Astra performs inference. The 30 s shown in the attempt-5 video is simulation time and excludes model waiting time; it does not represent 30 s of wall-clock execution.','仿真器在 Astra 推理期间暂停。第 5 次尝试视频中的 30 秒为仿真时间，不包含模型等待时间，不能解释为 30 秒实际运行时间。')}</p>
     <p>{c(`Across the full experiment, app-server audit counters record approximately ${(compute.audit.approximate_total_tokens/1e6).toFixed(1)}M total tokens, including ${(compute.audit.approximate_cached_input_tokens/1e6).toFixed(1)}M cached-input tokens and ${(compute.audit.approximate_output_tokens/1e6).toFixed(3)}M output tokens. These are cumulative experiment-level audit counts, not per-trajectory means, and cannot be used directly as API billing-token counts.`,`全实验 app-server 审计累计记录约 ${(compute.audit.approximate_total_tokens/1e8).toFixed(3)} 亿 total tokens，其中约 ${(compute.audit.approximate_cached_input_tokens/1e8).toFixed(3)} 亿为 cached input、${(compute.audit.approximate_output_tokens/1e4).toFixed(1)} 万为 output。这些数值为实验级累计审计量，不是每条轨迹均值，不能直接作为 API 计费 token。`)}</p>
    </div>
    <Details title={c('Attempt-level results and control interface','逐次结果与控制接口')}><DataTable caption={c('Open clutter · easy scene 0089 · seed 794782980','Open clutter · easy scene 0089 · seed 794782980')} headers={[c('Planner','规划器'),c('Termination','终止原因'),c('Sim. s','仿真秒'),c('Progress m','进展 m'),c('Final error m','最终误差 m'),c('Path m','路程 m'),c('Contact steps','接触步'),c('Arrival','到达')]} rows={results.clutter.map((r,i)=>[i===0?'Passage':c('Astra · attempt '+i,'Astra · 第 '+i+' 次尝试'),r.end,number(r.sim_s,2),number(r.progress_m,3),number(r.final_error_m,3),number(r.path_m,3),number(r.contact_steps),r.arrival?c('Yes','是'):c('No','否')])}/><Note>{c('Arrival tolerance is 0.5 m. The table covers the five completed adaptive attempts; attempt 2 includes operator-assisted recovery.','到达容差为 0.5 m。表格汇总五次已完成的适应尝试；第 2 次包含操作者协助恢复。')}</Note><Flow items={[c('History + height scan + route goal','历史 + 高度扫描 + 路线目标'),c('Astra or Passage','Astra 或 Passage'),'25 × 65D','ScaleBFM','29-joint PD']}/><p>{c('Each planner outputs a 0.5 s, 25-frame motion reference: root height, projected gravity, planar velocity, yaw rate, and 29 joint positions and velocities. Both use the same perceptive ScaleBFM tracker, 50 Hz control and 500 Hz physics. Astra uses xhigh reasoning; replanning is every six control steps. IsaacLab 2.3.2 / Isaac Sim 5.1 / PhysX.','每次输出 0.5 秒、25 帧运动参考，包含根部高度、投影重力、平面速度、偏航角速度及 29 关节的位置与速度。两者使用相同 perceptive ScaleBFM 跟踪器、50 Hz 控制和 500 Hz 物理。Astra 使用 xhigh 推理，每 6 个控制步重规划。环境为 IsaacLab 2.3.2 / Isaac Sim 5.1 / PhysX。')}<Cite ids={["isaaclab","isaacsim","physx"]}/></p><DataTable className="table-text" caption={c('Adaptation across five attempts','五次尝试中的适应过程')} headers={[c('Attempt','尝试'),c('Observed motion','运动结果'),c('Motion strategy','运动策略')]} rows={[
      ['1',c('1.561 m progress; collision and fall at 9.80 s.','前进 1.561 m，在 9.80 秒时碰撞并跌倒。'),c('Initial forward-motion reference.','初始前进运动参考。')],
      ['2',c('20.28 s upright; −0.024 m progress.','保持站立 20.28 秒，净进展 −0.024 m。'),c('Conservative standing with operator-assisted recovery.','偏向稳定站立，过程中包含操作者协助恢复。')],
      ['3',c('0.012 m progress in 8.0 s; 0.434 m path length.','8.0 秒内净进展 0.012 m，路程 0.434 m。'),c('Small periodic ankle and knee perturbations.','小幅周期性踝部与膝部扰动。')],
      ['4',c('0.159 m progress; displacement over the last 8 s stays below 0.10 m.','净进展 0.159 m，最后 8 秒位移低于 0.10 m。'),c('Combined speed and stride adjustments.','同时调整速度与步幅。')],
      ['5',c('2.598 m progress over 30 s of simulation, with zero falls and obstacle contacts; stops before the obstacle.','30 秒仿真时间内前进 2.598 m，无跌倒及障碍接触，在障碍前停止。'),c('Recorded G1 motion provides context for coordinated references.','加入记录的 G1 运动作为上下文，生成协调的运动参考。')]
    ]}/></Details>
    <Details title={c('Passage · low-ceiling demonstration','Passage · 低顶棚演示')}><p>{c('A multi-layer Passage planner and perceptive ScaleBFM tracker execute crouched motion under low clearance.','多层 Passage 规划器与感知型 ScaleBFM 追踪器在低净空条件下执行下蹲运动。')}</p><div className="media-grid"><MediaCard clip={get('ceiling-passage')}/></div></Details>
    <Details title={c('Additional clutter demonstrations','更多杂乱场景演示')}><p>{c('Passage and Astra navigating additional cluttered scenes.','Passage 与 Astra 在其他杂乱场景中的运动过程。')}</p><div className="media-grid">{humanoidSupplement.filter(r=>r.domain==='obstacles').map(clip=><MediaCard key={clip.id} clip={clip}/>)}</div></Details>
    <Conclusion paragraphs={c(["Passage reaches the goal in 13.18 s of simulation without a fall or obstacle contact. Astra’s five sequential attempts change from a collision and fall to stable forward motion. The fifth attempt advances 2.598 m over 30 s of simulation without falling or contacting an obstacle, then stops with 6.519 m remaining to the goal.","Shared scene memory and revised motion references improve stability and progress, while continuous obstacle traversal remains incomplete. Both planners use the same ScaleBFM tracker, so the observed difference lies in the references and planning process supplied to that tracker. The GPT–25 × 65D pipeline therefore provides an experimental setting for studying test-time reasoning; its model-turn latency currently limits real-time deployment."],["Passage 在 13.18 秒仿真时间内到达目标，期间无跌倒或障碍接触。Astra 的五次连续尝试从碰撞跌倒发展到稳定前进；第五次在 30 秒仿真时间内前进 2.598 m，保持无跌倒、无障碍接触，但随后停止，距目标仍有 6.519 m。","共享场景记忆与运动参考修订改善了稳定性和前进距离，持续穿过障碍区域仍未完成。两种规划器使用同一个 ScaleBFM tracker，性能差异体现在输入 tracker 的运动参考及其规划过程。当前 GPT–25 × 65D 管线适合用于研究 test-time reasoning，模型调用延迟仍限制其实时部署。"])}/>
  <div className="sec-links"><a href="joint-data/clutter.csv" download>{c('Attempt data CSV ↓','逐次数据 CSV ↓')}</a></div>
  </Section>;
}
Obstacles.meta={id:'obstacles',title:{en:'Obstacle Avoidance',zh:'避障'}};
